from _h import *

LESSONS = [
L("gr-tenses", "5.1", "Past simple o present perfect?", "L'errore n. 1 quando racconti",
  ["tense", "storytelling"], 20, 3,
  "Scegliere in un secondo il tempo giusto con una sola domanda: “c'è un momento finito?”",
  P("""<p>In italiano il passato prossimo copre due tempi inglesi. Da qui nasce l'errore. La domanda da farti è una sola:</p>
<p><strong>Si vede un momento finito (ieri, nel 2019, quando ero piccolo, durante il lockdown)?</strong><br>
→ Sì: <strong>past simple</strong> (<em>I went, I saw, I passed</em>).<br>
→ No, conta il risultato oggi o il periodo arriva fino a ora: <strong>present perfect</strong> (<em>I've been, I've never seen, I've lived here for…</em>).</p>""", h="La regola in una domanda"),
  VOC([("yesterday · last week · in 2019 · two years ago · when I was… · at 9 o'clock", "→ past simple"),
       ("ever · never · already · yet · just · so far", "→ present perfect"),
       ("for (+ durata) · since (+ inizio) fino a oggi", "→ present perfect (continuous)"),
       ("How long…? (fino a ora)", "→ present perfect · When…? → past simple")],
      h="Le parole spia"),
  P("""<p>Nel racconto il present perfect <em>apre</em> o <em>chiude</em>, il past simple <em>racconta</em>:</p>
<p><em>“<strong>I've been</strong> to England three times. The first time <strong>was</strong> in 2015. I <strong>went</strong> with my school and we <strong>stayed</strong> with a family. <strong>Since then</strong>, I<strong>'ve always wanted</strong> to go back.”</em></p>""", h="Lo schema “sandwich”"),
  FIX([("I have visited Rome last year.", "I visited Rome last year.", "“Last year” = momento finito.", "tense"),
       ("I live here since 2007.", "I've lived here since 2007.", "Dal 2007 fino a oggi.", "tense"),
       ("I know her for ten years.", "I've known her for ten years.", "Verbi di stato (know, be, have) con for/since: present perfect semplice.", "tense"),
       ("When have you started judo?", "When did you start judo?", "“When” chiede un momento → past simple.", "tense"),
       ("Did you ever go to London?", "Have you ever been to London?", "“Ever” nella vita fino a oggi → present perfect. Nota “been to”.", "tense"),
       ("I've finished school in 1990.", "I finished school in 1990.", "Data precisa.", "tense")]),
  QA([("Have you ever been abroad for work?", "Yes, I have. I went to Germany for a training course in 2019. It lasted a week, and I learnt a lot about industrial automation."),
      ("How long have you been teaching?", "I've been teaching for about ten years. I started in a school in Pordenone, and I've been at my current school since I got my permanent position."),
      ("What did you do last summer?", "I spent most of the summer at home, preparing for my exams, but in August we went to the mountains for a week. It was the first real holiday I'd had in two years.")],
     h="Allenamento con risposta modello"),
  TASK("<p>Racconta in 1 minuto <em>“a place you've visited more than once”</em> con lo schema sandwich: apri con present perfect, racconta la prima volta al past simple, chiudi con <em>Since then…</em></p>", 60),
),

L("gr-articles", "5.2", "Articoli: a, the o niente", "Mestieri, concetti generali, luoghi",
  ["articles", "calques"], 15, 5,
  "Eliminare le omissioni di “a/an” e gli usi di “the” in senso generale, i due errori che fai di più.",
  UL(["<strong>A / an</strong> con ogni singolare numerabile nominato per la prima volta o con i mestieri: <em>I'm <strong>a</strong> teacher · I have <strong>a</strong> car · It's <strong>a</strong> good idea</em>.",
      "<strong>Niente articolo</strong> per parlare di qualcosa in generale (plurali e non numerabili): <em><strong>Ø</strong> Technology changes fast · I love <strong>Ø</strong> pasta · <strong>Ø</strong> Teenagers need <strong>Ø</strong> space</em>.",
      "<strong>The</strong> quando sai di quale si parla: <em><strong>the</strong> school where I work · <strong>the</strong> film we saw yesterday · <strong>the</strong> internet</em>.",
      "Espressioni fisse senza articolo: <em>at school, at work, at home, in bed, by car, go to school, have lunch, next week, last year</em>."],
     h="Le tre regole che bastano"),
  FIX([("I am electronic technician.", "I'm an electronics technician.", "Mestiere → a/an.", "art"),
       ("The life is difficult.", "Life is difficult.", "Concetto generale.", "art"),
       ("The young people use the social media too much.", "Young people use social media too much.", "Categorie in generale → niente “the”.", "art"),
       ("I go to the work by the car.", "I go to work by car.", "Espressioni fisse.", "art"),
       ("It was very good experience.", "It was a very good experience.", "“Experience” numerabile (un'esperienza) → a.", "art"),
       ("I play the judo.", "I do judo.", "Sport: niente articolo (e si usa do/play/go).", "art")]),
  TASK("<p>Descrivi il tuo lavoro in 45 secondi. Poi riascoltati (registrati!) e conta ogni sostantivo singolare: ha il suo <em>a/the/my</em>?</p>", 45),
),

L("gr-questions", "5.3", "Fare domande (dirette e indirette)", "Per la Part 2 e la Part 3",
  ["functions", "negotiation"], 10, 5,
  "Fare domande senza errori d'ordine: servono per interagire nella Part 2 e 3.",
  UL(["Domanda diretta: ausiliare + soggetto + verbo: <em>What time <strong>does</strong> the course <strong>start</strong>?</em>",
      "Domanda indiretta (più cortese): ordine normale, niente do/does: <em>Could you tell me what time the course <strong>starts</strong>?</em>",
      "Rilanciare nella Part 3: <em>What do you think? · How about you? · Which one do you prefer? · Don't you think…?</em>",
      "Question tags per coinvolgere: <em>It's too expensive, <strong>isn't it</strong>? · We could try, <strong>couldn't we</strong>?</em>"]),
  FIX([("Where you work?", "Where do you work?", "Serve l'ausiliare.", "wo"),
       ("Do you know where is the station?", "Do you know where the station is?", "Indiretta: ordine della frase normale.", "wo"),
       ("What do you think about?", "What do you think (about it)?", "“About” da solo in fondo resta sospeso.", "calque")]),
  TASK("<p>Trasforma in domande indirette cortesi, ad alta voce:<br>1. How much is the ticket?<br>2. When does the museum close?<br>3. Is there a discount for students?<br>4. Where can I park?</p>", 60),
),

L("gr-connectors", "5.4", "Connettori che restano nel parlato", "Da “moreover” a “what's more”",
  ["connectors", "fluency", "storytelling"], 10, 9,
  "Sostituire i connettori da scritto con 8 connettori parlati da usare davvero.",
  P("""<p>Per iscritto usi bene <em>Moreover, In addition, To sum up</em>. Parlando spariscono, perché sono lunghi e formali. Tieni invece questi otto, brevi e naturali:</p>"""),
  VOC([("Also… / And another thing…", "aggiungere"), ("What's more… / On top of that…", "in più (enfatico)"),
       ("But… / Even so…", "contrasto"), ("On the other hand…", "d'altra parte"),
       ("For example… / For instance…", "esempio"), ("That's why…", "ecco perché"),
       ("So…", "quindi / conseguenza"), ("So, all in all…", "per concludere")],
      h="Gli 8 connettori parlati"),
  FIX([("Moreover the price is too high.", "What's more, it's too expensive.", "Più naturale nel parlato.", "conn"),
       ("In conclusion, to sum up, finally…", "So, all in all, …", "Un solo connettore per chiudere.", "conn"),
       ("Also I like it.", "I also like it. / I like it, too.", "“Also” va prima del verbo principale.", "wo")]),
  TASK("<p>Parla per 1 minuto di <em>“the advantages and disadvantages of living in a small town”</em> usando almeno 5 degli 8 connettori. Chiedi a qualcuno di contarli.</p>", 60),
),

L("gr-prepositions", "5.5", "Le preposizioni che sbagli", "Le 25 combinazioni che contano",
  ["prepositions", "calques"], 15, 10,
  "Fissare le combinazioni verbo/aggettivo + preposizione che compaiono sempre all'esame.",
  VOC([("depend <strong>on</strong>", "non “from”"), ("arrive <strong>at</strong> / <strong>in</strong>", "mai “to”"),
       ("interested <strong>in</strong>", ""), ("good <strong>at</strong>", "bravo in"), ("married <strong>to</strong>", "sposato con"),
       ("listen <strong>to</strong>", ""), ("wait <strong>for</strong>", ""), ("pay <strong>for</strong> something", ""),
       ("worried <strong>about</strong>", ""), ("afraid <strong>of</strong>", ""), ("responsible <strong>for</strong>", ""),
       ("similar <strong>to</strong> · different <strong>from</strong>", ""), ("think <strong>about</strong> / <strong>of</strong>", ""),
       ("discuss something", "senza “about”!"), ("explain something <strong>to</strong> someone", "non “explain me”"),
       ("<strong>at</strong> the weekend (UK) · <strong>on</strong> Monday · <strong>in</strong> July · <strong>at</strong> 8 o'clock", "tempo"),
       ("<strong>at</strong> school / work / home · <strong>in</strong> Pordenone / Italy", "luogo"),
       ("<strong>by</strong> car / train · <strong>on</strong> foot", "mezzi"),
       ("<strong>for</strong> two years · <strong>since</strong> 2015 · two years <strong>ago</strong>", "durata")],
      h="La lista (da ripassare la sera prima)"),
  FIX([("It depends from the weather.", "It depends on the weather.", "", "prep"),
       ("Can you explain me the rules?", "Can you explain the rules to me?", "", "prep"),
       ("We discussed about the project.", "We discussed the project.", "", "prep"),
       ("I'm good in electronics.", "I'm good at electronics.", "", "prep"),
       ("I'm married with Anna.", "I'm married to Anna.", "", "prep"),
       ("I arrived to Venice at 10.", "I arrived in Venice at 10.", "", "prep")]),
  TASK("<p>Rispondi usando la preposizione giusta: <br>1. What are you good at? <br>2. What does your mood depend on? <br>3. What are you worried about at the moment? <br>4. What are your students interested in?</p>", 90),
),

L("gr-conditionals", "5.6", "Would, could, might", "Ipotesi e proposte per Part 3 e 4",
  ["negotiation", "tense"], 15, 10,
  "Usare i condizionali per proporre e ipotizzare, senza il “would” dopo “if”.",
  UL(["<strong>Proporre (Part 3)</strong>: <em>We <strong>could</strong> ask the council. · It <strong>might</strong> be cheaper to… · That <strong>would</strong> be great.</em>",
      "<strong>Ipotesi reali</strong>: <em>If it <strong>rains</strong>, we<strong>'ll</strong> move inside.</em> (if + presente, will)",
      "<strong>Ipotesi immaginarie</strong>: <em>If I <strong>had</strong> more time, I<strong>'d</strong> learn the guitar.</em> (if + past, would)",
      "<strong>Consiglio</strong>: <em>If I <strong>were</strong> you, I<strong>'d</strong>…</em>"]),
  FIX([("If I would have time, I would travel more.", "If I had time, I'd travel more.", "Mai “would” nella parte con if.", "tense"),
       ("If it will rain, we stay inside.", "If it rains, we'll stay inside.", "Il futuro va nell'altra metà.", "tense"),
       ("It would be more better.", "It would be better.", "“Better” è già comparativo.", "")]),
  QA([("If you could live anywhere in the world, where would you live?", "I think I'd live in Scotland for a while. I love the landscapes, and it would be a great way to improve my English. But I don't think I could live there forever — I'd miss the food and the sun!"),
      ("What would you do if you won a lot of money?", "First, I'd help my family. Then I'd probably take a year off to travel, and maybe I'd open a small lab where young people could build their own projects.")],
     h="Allenamento con risposta modello"),
  TASK("<p>Completa ad alta voce in modo personale: <br>1. If I pass this exam, … <br>2. If I had more free time, … <br>3. If I were the head teacher, … <br>4. We could organise the event outside, but if it…</p>", 60),
),

L("gr-calques", "5.7", "Calchi dall'italiano: la top 30", "Le frasi che “suonano italiane”",
  ["calques", "fluency"], 20, 11,
  "Riconoscere e sostituire le frasi tradotte parola per parola che l'esaminatore nota subito.",
  P("""<p>Il calco non è un errore di grammatica: è una frase corretta nella forma ma che un inglese non direbbe mai. Qui sotto i più frequenti per un italiano, divisi per tipo. Leggi la colonna verde ad alta voce finché diventa naturale.</p>"""),
  FIX([("I have 50 years.", "I'm 50.", "L'età si “è”.", "calque"),
       ("I am agree.", "I agree.", "", "calque"),
       ("It makes cold.", "It's cold.", "", "calque"),
       ("I make a photo.", "I take a photo.", "", "calque"),
       ("I make a shower.", "I have a shower.", "", "calque"),
       ("I make a question.", "I ask a question.", "", "calque"),
       ("I do a party.", "I have / throw a party.", "", "calque"),
       ("I take a coffee.", "I have a coffee.", "", "calque"),
       ("I have right.", "I'm right.", "", "calque"),
       ("I have need of…", "I need…", "", "calque"),
       ("It serves to…", "It's used for… / It's useful for…", "", "calque"),
       ("How do you say…? (a una persona)", "What's the word for…?", "", "calque")],
      h="Verbi: make/do/have/take"),
  FIX([("Actually I work in a school.", "At the moment / Currently I work at a school.", "“Actually” = in realtà, non “attualmente”.", "calque"),
       ("Eventually I will call you.", "I might call you. / If necessary, I'll call you.", "“Eventually” = alla fine.", "calque"),
       ("I'm very sensible to noise.", "I'm very sensitive to noise.", "“Sensible” = assennato.", "calque"),
       ("A big argument of the lesson.", "An important topic of the lesson.", "“Argument” = litigio / tesi.", "calque"),
       ("My parents are very educated with guests.", "My parents are very polite to guests.", "“Educated” = istruito.", "calque"),
       ("I assisted to the meeting.", "I attended the meeting.", "“Assist” = aiutare.", "calque"),
       ("I'm preoccupied for the exam.", "I'm worried about the exam.", "", "calque"),
       ("The library (dove compri libri)", "The bookshop", "Library = biblioteca.", "calque")],
      h="Falsi amici"),
  FIX([("Since two years.", "For two years.", "", "prep"),
       ("In my opinion I think…", "I think…", "", "calque"),
       ("How can I say…", "How can I put it…", "", "calque"),
       ("I'm going to the mountain.", "I'm going to the mountains.", "Montagna in generale = plurale.", "calque"),
       ("It's a problem of money.", "It's a money problem. / It's about money.", "", "calque"),
       ("There are many people that…", "Lots of people…", "", "calque"),
       ("I know him from 2010.", "I've known him since 2010.", "", "tense"),
       ("Good appetite!", "Enjoy your meal!", "", "calque"),
       ("We are in five.", "There are five of us.", "", "calque"),
       ("Also I.", "Me too.", "", "calque")],
      h="Espressioni e strutture"),
  TASK("<p>L'esaminatore dice le frasi in italiano (o leggile tu dalla colonna rossa) e tu dici subito la versione inglese naturale. Giro completo in 2 minuti.</p>", 120),
),
]
