from _h import *

SELF = UL(["<strong>Part 1</strong> — Ho risposto sempre con almeno 2 frasi (risposta + motivo/esempio)?",
           "<strong>Part 2</strong> — Ho usato la frase funzionale giusta all'inizio (scusa, proposta, richiesta…)?",
           "<strong>Part 3</strong> — Ho commentato almeno due idee dell'esaminatore e siamo arrivati a una decisione?",
           "<strong>Part 4</strong> — Ho parlato per quasi 2 minuti con UNA storia e le 5 tappe?",
           "<strong>Errori</strong> — Riascoltando la registrazione: quanti errori di tempo verbale? articoli? calchi? Scrivi i 3 più frequenti e ripassa la lezione collegata."],
          h="Autovalutazione (dopo aver riascoltato la registrazione)")

HOW = P("""<p>Registra tutta la simulazione con il telefono. Non fermarti e non correggerti oltre un “sorry, I mean…”. Leggi solo il compito della parte in corso: il resto della pagina è per dopo. In alternativa, incolla il messaggio “ESERCIZIO 2 — Simulazione completa” nella chat del progetto e fai la prova a voce con Claude.</p>""", h="Come usarla")


def mock(id, n, title, sub, day, p1, p2, p3, p4):
    return L(id, n, title, sub, ["mock", "strategy"], 30, day,
             "Fare una prova completa nei tempi reali (13 minuti) e trovare i 3 errori su cui lavorare.",
             HOW,
             TASK("<p>L'esaminatore ti fa queste domande, una alla volta. Rispondi in 20–30 secondi ciascuna.</p><ol>" +
                  "".join(f"<li>{q}</li>" for q in p1) + "</ol>", 180, h="Part 1 · Domande personali (3 min)"),
             TASK("<p><strong>Role-play 1:</strong> " + p2[0] + "</p><p><strong>Role-play 2:</strong> " + p2[1] + "</p>", 180, h="Part 2 · Role-play (3 min)"),
             p3,
             TASK("<p>Timer: 30 secondi per gli appunti, poi 2 minuti di parola. Il modello è qui sotto, da aprire solo alla fine.</p>", 120, 30, h="Part 4 · Monologo (4 min)"),
             p4,
             SELF)


LESSONS = [
mock("mk-a", "6.1", "Simulazione A", "Lavoro, cibo, viaggi · scuse e inviti · evento scolastico · una persona", 12,
     ["Where are you from, and what's it like there?", "How do you usually spend your weekends?",
      "What's the best meal you've had recently?", "Have you ever travelled abroad for work or study?",
      "Would you like to change anything about your job?"],
     ["I'm your friend. I lent you a book and you spilled coffee on it. I'll start.",
      "You want to invite your neighbour to a barbecue on Sunday. You start."],
     NEG("Your town wants to organise a festival to attract tourists. You have a budget of €10,000. Discuss the ideas and agree on the best one.",
         ["A food festival with local products", "An outdoor cinema in the main square", "A cycling race"],
         ["A music festival with local bands", "A medieval market", "A photography competition"],
         h="Part 3 · Discussione (3–4 min)"),
     MONO("Talk about a teacher or coach who was important to you.",
          ["Who were they?", "What did they teach you?", "Why do you still remember them?"],
          ["coach / teacher – name", "when & where", "one episode", "what changed", "today"],
          ["The person I'd like to talk about is my electronics teacher at secondary school, Mr Bianchi.",
           "I was about sixteen, and to be honest I wasn't a very motivated student. I liked practical things, but I found the theory boring and I often didn't do my homework.",
           "One day he gave me a project to do on my own: a small alarm circuit for the school lab. At first I thought it was a punishment! But I spent weeks on it, and when it finally worked, he asked me to present it to the whole class.",
           "That moment changed my attitude completely. I realised that theory was simply the way to make things work. After that, my marks improved a lot.",
           "Looking back, I think that's probably why I became a lab teacher. And now, when I see an unmotivated student, I try to do exactly what he did with me: give them something real to build."],
          [("Should teachers be friends with their students?", "I don't think they should be friends, but they should be approachable. Students need to feel they can ask for help, but there has to be some distance."),
           ("What makes a good lesson?", "For me, a good lesson has a clear goal, some practical activity and a moment where students have to think for themselves.")],
          h="Part 4 · Il compito e il modello")),

mock("mk-b", "6.2", "Simulazione B", "Tecnologia, casa, sport · lamentele e consigli · team building · un traguardo", 13,
     ["What do you do?", "How much do you use technology in your free time?",
      "What do you like about the place where you live?", "What sport or activity did you enjoy as a child?",
      "Is there anything you'd like to learn in the next few years?"],
     ["I'm a shop assistant. You bought a phone case last week and it has already broken. I'll start.",
      "Your friend wants to start running but doesn't know how. Give some advice. You start."],
     NEG("Your school wants to make students more aware of environmental issues. Discuss the ideas and choose the two most effective.",
         ["A school vegetable garden", "A competition to reduce plastic", "A visit to a recycling plant"],
         ["A talk by an environmental scientist", "A 'car-free day' for teachers and students", "Solar panels built by students"],
         h="Part 3 · Discussione (3–4 min)"),
     MONO("Talk about something you achieved that required a lot of effort.",
          ["What was it?", "Why was it difficult?", "How did you feel when you achieved it?"],
          ["what – black belt / exam", "when", "difficulty", "the day", "since then"],
          ["I'd like to talk about the day I got my black belt in judo.",
           "I had been training for many years, but the exam was much harder than I expected. You have to show a series of techniques perfectly, and you also have to fight.",
           "The problem was that, a few months before the exam, I injured my shoulder, so I couldn't train properly for several weeks. At one point I thought about giving up and waiting for the next year. But my teacher convinced me to try, and I trained in a different way, focusing on technique instead of strength.",
           "On the day of the exam I was incredibly nervous, but once I started, I just concentrated on one technique at a time. When the examiners told me I had passed, I felt a mix of relief and pride.",
           "Since then, I've always remembered that you don't need perfect conditions to succeed. You need to adapt. And I'm using exactly that lesson now, with this English exam."],
          [("Is it better to succeed easily or after a lot of effort?", "After a lot of effort, definitely. You appreciate the result more, and you learn things along the way that are useful later."),
           ("Do you think competition is good for young people?", "In moderation, yes. It teaches them to deal with pressure and to lose, but it shouldn't become the only thing that matters.")],
          h="Part 4 · Il compito e il modello")),

mock("mk-c", "6.3", "Simulazione C", "Famiglia, media, meteo · richieste e cambi di programma · budget giovani · un luogo", 14,
     ["Tell me about your family.", "How do you usually keep up with the news?",
      "What's your favourite time of year? Why?", "What did you do on your last holiday?",
      "Do you think people are too busy these days?"],
     ["I'm your colleague. I can't come to the meeting we arranged for tomorrow. I'll start.",
      "You need to borrow a friend's bike for a week. You start."],
     NEG("A local company wants to sponsor something for your town's teenagers. Discuss the options and decide together on the best one.",
         ["Free summer sports camps", "A music recording studio", "Scholarships for study abroad"],
         ["A new public Wi-Fi network", "A careers fair with local companies", "A community garden"],
         h="Part 3 · Discussione (3–4 min)"),
     MONO("Talk about a place where you feel relaxed.",
          ["Where is it?", "What do you do there?", "Why does it help you relax?"],
          ["where", "how often / with whom", "one memory", "why relaxing", "conclusion"],
          ["The place where I feel most relaxed is the mountains, in particular a small village in Carnia where my family used to go every summer.",
           "It's about an hour and a half from my house. There isn't much there: a church, a bar, a few houses and lots of woods. We usually go there for a few days in August.",
           "My favourite memory is from last summer. I got up very early, before everyone else, and walked up to a meadow above the village. There was nobody around, just the sound of the cows' bells in the distance. I sat there for almost an hour, just watching the light change on the mountains.",
           "It helps me relax because there's no pressure: no emails, no timetable, and the phone signal is terrible, which is actually a good thing!",
           "So, all in all, it's a simple place, but it's where I really recharge my batteries before the school year starts."],
          [("Do people need to go on holiday to relax?", "Not necessarily. I think it's more important to have small moments of rest every day, like a walk or a hobby. Holidays help, but they aren't enough on their own."),
           ("Is it harder to relax today than in the past?", "I think so, because we're always connected. Work can reach us anywhere, at any time, so we have to learn to switch off on purpose.")],
          h="Part 4 · Il compito e il modello")),

L("mk-day", "6.4", "Il giorno dell'esame", "Checklist della vigilia e dei 13 minuti",
  ["strategy", "fluency", "format"], 10, 14,
  "Arrivare all'esame con la testa libera e una routine precisa per ogni parte.",
  UL(["Ripassa solo: lezione 2.1 (frasi Part 2), 3.1 (frasi Part 3), 5.5 (preposizioni). Niente cose nuove.",
      "Fai un allenamento rapido di Part 1 a voce, 10 minuti, poi basta.",
      "Prepara 3 storie jolly per la Part 4 (una persona, un traguardo, un problema risolto): si adattano a quasi ogni argomento.",
      "Dormi. La fluidità dipende più dal sonno che da un'ora di studio in più."],
     h="La sera prima"),
  UL(["Parla in inglese per 10 minuti prima di entrare (a voce bassa, in macchina, con un podcast).",
      "Part 1: prima frase = la domanda rigirata (<em>Do you like…? → Yes, I really like…</em>). Poi motivo + esempio.",
      "Part 2: la prima parola è la funzione (<em>Sorry… / Congratulations… / Could you…</em>).",
      "Part 3: chiedi le idee dell'esaminatore <em>prima</em> di difendere le tue. Chiudi con <em>So, shall we go for…?</em>",
      "Part 4: nei 30 secondi scrivi 5 parole e <em>PAST</em>. Una storia sola.",
      "Se sbagli: <em>Sorry, I mean…</em> e vai avanti. Un errore corretto vale come una frase giusta."],
     h="Il giorno dell'esame"),
  PH([("Le 6 frasi da avere pronte", [("Sorry, could you repeat that, please?", ""), ("That's a good question. Let me think…", ""),
                                      ("I see what you mean, but…", ""), ("What if we combined the two ideas?", ""),
                                      ("I'd like to talk about…", ""), ("Looking back, I think…", "")])], h="Kit di emergenza"),
  TASK("<p>Respira, avvia il timer e di' ad alta voce in inglese cosa farai nelle 4 parti dell'esame, come se lo spiegassi a un amico. Poi chiudi il computer.</p>", 60),
),
]
