from _h import *


def topic(id, n, title, sub, tags, day, goal, qa, voc, fix, drill):
    return L(id, n, title, sub, tags, 15, day, goal,
             QA(qa, note="Prova prima a rispondere a voce (20–30 secondi), poi apri il modello. I modelli sono esempi: cambia i dettagli con quelli veri della tua vita, tieni la struttura."),
             VOC(voc), FIX(fix),
             TASK("<p>Simulazione rapida: rispondi senza pause lunghe, circa 30 secondi a domanda.</p><ol>" +
                  "".join(f"<li>{q}</li>" for q in drill) + "</ol>", 150))


LESSONS = [
L("p1-intro", "1.0", "La formula della Part 1", "Risposta + motivo + esempio, in 20–30 secondi",
  ["strategy", "tense", "fluency"], 10, 1,
  "Dare risposte né troppo corte (“Yes, I do.”) né troppo lunghe, con il tempo verbale che la domanda ti suggerisce.",
  P("""<p>Ogni risposta della Part 1 ha tre pezzi: <strong>A</strong>nswer (rispondi subito), <strong>R</strong>eason (perché), <strong>E</strong>xample (un esempio concreto dalla tua vita). Totale: 2–4 frasi.</p>
<p><em>Do you like cooking?</em> → <strong>A</strong> <em>Yes, I do, especially at the weekend.</em> <strong>R</strong> <em>It helps me relax after a busy week at school.</em> <strong>E</strong> <em>Last Sunday, for example, I made a risotto for the whole family.</em></p>""", h="A · R · E"),
  P("""<p>La domanda ti regala il tempo verbale. Riprendilo nella risposta:</p>
<ul class="plain">
<li><em>Do you…? / How often…?</em> → <strong>present simple</strong> (<em>I usually…</em>)</li>
<li><em>Have you ever…?</em> → <strong>present perfect</strong> per dire sì/no, poi <strong>past simple</strong> per i dettagli (<em>Yes, I have. I went there in 2018 and…</em>)</li>
<li><em>What did you do…? / When was the last time…?</em> → <strong>past simple</strong></li>
<li><em>Would you like to…? / If you could…</em> → <strong>would</strong> (<em>I'd love to…</em>)</li>
<li><em>Are you going to… / What are your plans…?</em> → <strong>going to / present continuous</strong></li>
</ul>""", h="La domanda ti dà il tempo verbale"),
  FIX([("Have you ever been to London? — Yes, I have been there in 2019.", "Yes, I have. I went there in 2019.", "Il “sì” con present perfect, i dettagli con la data al past simple.", "tense"),
       ("Yes.", "Yes, I do — mainly because…", "Una sola parola non mostra il tuo livello.", ""),
       ("I like very much cooking.", "I really like cooking. / I like cooking very much.", "“Very much” non va tra verbo e complemento.", "wo")]),
  TASK("<p>Rispondi con la formula A·R·E: <br>1. Do you prefer mornings or evenings? <br>2. Have you ever studied abroad? <br>3. What did you do last weekend? <br>4. Would you like to learn another language?</p>", 120),
),

topic("p1-phone", "1.1", "Telefono e comunicazione", "Chiamate, messaggi, social",
  ["phone", "tech"], 2,
  "Parlare di come comunichi, confrontando telefonate e messaggi.",
  [("Do you prefer calling people or sending messages?",
    "It depends on who I'm talking to. With my family I usually call, because it's quicker and more personal. With colleagues, on the other hand, I prefer sending messages, so they can answer when they have time.",
    "Nota <em>on the other hand</em>: un connettore che nel parlato ti sparisce spesso."),
   ("How much time do you spend on your phone every day?",
    "Probably more than I'd like to admit! I'd say about two hours, mostly for work: I check the school's platform, answer emails and prepare material for my lessons. In the evening I try to leave it in another room."),
   ("Have you ever lost your phone?",
    "Yes, I have, once. I left it on a train a few years ago and I only noticed when I got home. Luckily, someone handed it in at the station and I got it back the next day.",
    "Present perfect per il “sì”, poi tutto al past simple."),
   ("Do you think people use their phones too much?",
    "Yes, I do, especially young people. I see it every day at school: during the break most students are looking at a screen instead of talking to each other. That said, phones are also very useful for studying."),
   ("How has communication changed since you were a child?",
    "It has changed completely. When I was a child we only had a landline at home and we called our relatives on Sundays. Now we can make video calls for free, anywhere in the world.",
    "<em>has changed</em> (fino a oggi) vs <em>when I was a child we had</em> (passato concluso).")],
  [("landline", "telefono fisso"), ("to text someone", "mandare un messaggio a qualcuno"),
   ("to make a (video) call", "fare una (video)chiamata"), ("to hand something in", "consegnare (un oggetto trovato)"),
   ("to be glued to your phone", "essere incollato al telefono"), ("notifications", "notifiche")],
  [("I make a call to my mother.", "I call my mother. / I give my mother a call.", "“Make a call” esiste, ma “make a call to” è pesante.", "calque"),
   ("I have lost my phone last year.", "I lost my phone last year.", "“Last year” = tempo concluso → past simple.", "tense"),
   ("I send messages at my colleagues.", "I send messages to my colleagues.", "Send something <strong>to</strong> someone.", "prep")],
  ["Who do you talk to most on the phone?", "Do you like using social media? Why?", "What was your first mobile phone like?", "Should children have a smartphone?"]),

topic("p1-manners", "1.2", "Buone maniere", "Cortesia, regole, differenze culturali",
  ["manners", "family"], 2,
  "Dare opinioni su comportamenti educati e maleducati con esempi concreti.",
  [("What do you think are good manners?",
    "For me, good manners are about respect: saying please and thank you, arriving on time and listening when other people are speaking. In my job I also think it's important to greet everyone, not just the people you know."),
   ("Were your parents strict about manners when you were young?",
    "Yes, they were, quite strict. For example, we always had to wait until everyone was sitting at the table before we started eating, and we weren't allowed to use the phone during dinner.",
    "<em>had to / weren't allowed to</em>: obbligo e divieto al passato."),
   ("Are manners different in other countries?",
    "Definitely. When I was in England, I noticed that people queue very patiently and say sorry all the time, even when it isn't their fault. In Italy we're a bit more relaxed about queuing!"),
   ("What behaviour do you find rude?",
    "I find it rude when people talk loudly on the phone in public places, like on a bus. Another thing that annoys me is when someone checks their phone while you're talking to them."),
   ("Do you think young people today are less polite?",
    "Not really. I work with teenagers and most of them are polite, they just show it in a different way. They might not say “good morning” to everyone, but they're often very helpful.")],
  [("to queue (up)", "fare la fila"), ("rude / impolite", "maleducato"), ("to greet", "salutare"),
   ("to interrupt", "interrompere"), ("it annoys me when…", "mi dà fastidio quando…"), ("to be allowed to", "avere il permesso di")],
  [("It's educated to say thank you.", "It's polite to say thank you.", "“Educated” = istruito, non educato!", "calque"),
   ("I find rude when people shout.", "I find it rude when people shout.", "Serve “it” dopo find.", "wo"),
   ("When I was young I have learnt good manners.", "When I was young, I learnt good manners.", "“When I was young” → past simple.", "tense")],
  ["Is it rude to be late in your country?", "Who taught you good manners?", "Should schools teach manners?", "What do you do if someone is rude to you?"]),

topic("p1-food", "1.3", "Cibo e bevande", "Abitudini, cucina, ristoranti",
  ["food", "family", "health"], 2,
  "Descrivere abitudini alimentari e un pasto speciale senza calchi (“make a dinner”, “eat a pizza”…).",
  [("What's your favourite food?",
    "I'd say risotto, because it's typical of where I live, in the north-east of Italy. There are so many versions: with mushrooms, with radicchio or with seafood. My favourite is the one my mother makes with pumpkin."),
   ("Do you prefer eating at home or in restaurants?",
    "Usually at home, because it's cheaper and healthier. But I enjoy going out for a pizza with friends at the weekend, maybe once or twice a month. It's more about spending time together than about the food."),
   ("Can you cook?",
    "Yes, I can, although I'm not a great cook. I can make simple dishes like pasta, soups and grilled vegetables. When I have more time, at the weekend, I try new recipes that I find online."),
   ("Has your diet changed in recent years?",
    "Yes, it has. Since I started running more regularly, I've been eating less meat and more fruit and vegetables. I've also cut down on sugar, which was quite hard at the beginning.",
    "<em>Since</em> + past simple, poi present perfect continuous: la struttura “da quando”."),
   ("Tell me about a special meal you remember.",
    "I remember my parents' fortieth wedding anniversary. We had lunch at a restaurant in the hills, the whole family was there and the food was excellent. What I remember most, though, is my father's speech at the end.")],
  [("to cut down on", "ridurre"), ("a dish", "un piatto (la pietanza)"), ("a recipe", "una ricetta"),
   ("homemade", "fatto in casa"), ("to eat out", "mangiare fuori"), ("a balanced diet", "un'alimentazione equilibrata")],
  [("I make a dinner with my friends.", "I have dinner with my friends.", "Il pasto si “ha”: have breakfast / lunch / dinner (senza articolo).", "calque"),
   ("The pasta is my favourite food.", "Pasta is my favourite food.", "Parlando in generale: niente “the”.", "art"),
   ("I'm used to eat at 1 o'clock.", "I usually eat at 1 o'clock.", "“Be used to” vuole -ing e significa “essere abituato”; per le abitudini usa “usually”.", "calque")],
  ["What did you have for breakfast today?", "Is there a dish from your region you'd recommend?", "Do you think fast food is a problem?", "Who does the cooking in your family?"]),

topic("p1-education", "1.4", "Scuola e studio", "Ricordi di scuola, imparare, formazione",
  ["education", "work"], 3,
  "Parlare della tua esperienza di studente e di insegnante, usando bene “used to” e il past simple.",
  [("What do you remember about your secondary school?",
    "I went to a technical school, and what I remember most is the lab: we spent hours building small circuits. I wasn't the best student in theory, but I loved the practical part. That's probably why I teach lab subjects today."),
   ("What subject did you enjoy most at school?",
    "Electronics, without a doubt. I enjoyed understanding how things work. On the other hand, I didn't like history very much, mainly because we had to learn lots of dates by heart."),
   ("Do you think it's important to keep learning as an adult?",
    "Absolutely. Technology changes so fast that if you stop learning, you fall behind. At the moment, for example, I'm studying for this English exam and I'm also taking a course to get a teaching qualification."),
   ("Would you like to study something new in the future?",
    "Yes, I'd like to take a course in robotics, because my students are really interested in it. I think it would help me make my lessons more practical and up to date."),
   ("How is school different today from when you were a student?",
    "The biggest difference is technology. When I was a student we used to write everything by hand, while now students use tablets and online platforms. Teachers also used to be much stricter.",
    "<em>used to</em> + verbo base = abitudine passata che non c'è più.")],
  [("to learn by heart", "imparare a memoria"), ("to fall behind", "restare indietro"), ("a qualification", "un titolo / una certificazione"),
   ("a technical school", "un istituto tecnico / professionale"), ("to take / pass / fail an exam", "sostenere / superare / non superare un esame"), ("marks (UK) / grades (US)", "voti")],
  [("I have done an exam yesterday.", "I took an exam yesterday.", "“Yesterday” → past simple; e l'esame si “take”, non “do” (in parlato UK “do” è tollerato, “take” è più sicuro).", "tense"),
   ("I study English since two years.", "I've been studying English for two years.", "“Da due anni” = present perfect continuous + for.", "tense"),
   ("I teach in the school Zanussi.", "I teach at the Zanussi school.", "Ordine: nome + school; preposizione “at”.", "wo")],
  ["What kind of student were you?", "Did you have a favourite teacher? Why?", "Is it better to study alone or in a group?", "Should school last longer or shorter?"]),

topic("p1-travel", "1.5", "Viaggi e trasporti", "Vacanze, mezzi di trasporto, esperienze all'estero",
  ["travel", "freetime"], 3,
  "Raccontare viaggi senza confondere past simple e present perfect.",
  [("Do you like travelling?",
    "Yes, I love it, although I don't travel as much as I'd like to. I prefer short trips, like a weekend in a city I don't know, rather than long holidays. Last spring, for example, I spent three days in Vienna."),
   ("How do you usually get to work?",
    "I usually drive, because the school is about twenty kilometres from where I live and the public transport isn't very good. When the weather is nice, I sometimes cycle part of the way."),
   ("What's the most interesting place you've ever visited?",
    "Probably Edinburgh. I went there about ten years ago with some friends. I loved the old town and the castle, and the people were really friendly. The weather, on the other hand, was terrible!",
    "Domanda al present perfect (<em>'ve ever visited</em>), racconto al past simple (<em>I went… I loved…</em>)."),
   ("Do you prefer travelling alone or with other people?",
    "With other people, definitely. I think travelling is more fun when you can share the experience. Also, it's safer and cheaper, because you can split the costs."),
   ("Where would you like to go in the future?",
    "I'd love to go to Japan. I'm interested in the culture, and as I practise judo, it would be amazing to train in a dojo there. I hope I'll be able to go in the next few years.")],
  [("a trip / a journey / travel", "gita-viaggio breve / tragitto / il viaggiare (non numerabile)"), ("to get to", "arrivare a"),
   ("to split the costs", "dividere le spese"), ("sightseeing", "visite turistiche"), ("a return ticket", "biglietto andata e ritorno"), ("to go abroad", "andare all'estero")],
  [("I have been in Spain last summer.", "I went to Spain last summer.", "Tempo concluso → past simple; e con i viaggi si usa “go to”.", "tense"),
   ("I did a travel to Japan.", "I went on a trip to Japan.", "“Travel” è non numerabile; si dice a trip / a journey.", "calque"),
   ("I arrived to the airport.", "I arrived at the airport.", "Arrive <strong>at</strong> (luogo) / <strong>in</strong> (città, nazione). Mai “to”.", "prep")],
  ["What was your last holiday like?", "Do you prefer the sea or the mountains?", "What do you always take with you when you travel?", "Is public transport good where you live?"]),

topic("p1-work", "1.6", "Lavoro", "Il tuo lavoro, colleghi, ambizioni",
  ["work", "education"], 3,
  "Descrivere il lavoro di insegnante in modo chiaro, con articoli e preposizioni corretti.",
  [("What do you do?",
    "I'm a teacher. I work at a vocational school in Pordenone, where I teach lab subjects in the electrical and electronics department. Most of my students are between fifteen and nineteen.",
    "<em>I'm <strong>a</strong> teacher · I work <strong>at</strong> a school · <strong>in</strong> Pordenone</em>."),
   ("What do you like most about your job?",
    "I really like the practical side. When students finally see a circuit working after they've built it themselves, their faces light up. That moment makes all the hard work worth it."),
   ("Is there anything you find difficult about your job?",
    "Yes. Sometimes it's hard to keep everyone motivated, because the classes are quite mixed. Some students are very interested, while others would rather be somewhere else. I try to use real-life examples to get them involved."),
   ("How long have you been doing this job?",
    "I've been teaching for several years now, but I only got a permanent position recently, after passing a national competition. Before that, I worked in the private sector as a technician.",
    "<em>How long have you been…</em> → rispondi con present perfect continuous, poi i fatti con data al past simple."),
   ("Would you like to change your job in the future?",
    "Not really. I'm happy where I am. However, I'd like to take on more responsibility at school, for example coordinating projects with local companies, so that students can do work placements.")],
  [("a vocational school", "istituto professionale"), ("a permanent position", "un posto di ruolo / a tempo indeterminato"),
   ("a work placement / internship", "tirocinio / stage"), ("colleagues", "colleghi"),
   ("to take on responsibility", "prendersi responsabilità"), ("a competition (public exam)", "concorso")],
  [("I work like teacher.", "I work as a teacher.", "“Like” = simile a; “as” = in qualità di.", "calque"),
   ("I teach since 2015.", "I've been teaching since 2015.", "Azione iniziata nel passato e ancora in corso.", "tense"),
   ("I have many works to do.", "I have a lot of work to do.", "“Work” (lavoro da fare) non è numerabile.", "vocab")],
  ["Why did you choose this job?", "What's a typical working day like for you?", "Do you prefer working alone or in a team?", "What job did you want to do as a child?"]),

topic("p1-freetime", "1.7", "Tempo libero e sport", "Hobby, judo, corsa, weekend",
  ["freetime", "sport", "health"], 7,
  "Parlare delle tue passioni con entusiasmo e precisione: è il tema dove puoi brillare.",
  [("What do you do in your free time?",
    "I'm quite active. I practise judo, which I've been doing for many years, and I go running two or three times a week. When I want to relax, I like watching films or going for a walk along the river near my house."),
   ("How did you start doing judo?",
    "I started when I was a child. A friend of mine was going to a judo club and I went with him one day to watch. I liked it so much that I joined the following week, and I've never stopped since."),
   ("Why do you like running?",
    "Mainly because it clears my mind. After a day at school I need some time on my own, and running is perfect for that. I also like tracking my progress on an app: it keeps me motivated."),
   ("Do you prefer team sports or individual sports?",
    "I prefer individual sports, although judo is a bit of both: you fight alone, but you train with a group and you depend on your partners. I like the fact that the result depends on you."),
   ("Is there a new hobby you would like to try?",
    "Yes, I'd like to try photography. I often see beautiful landscapes when I'm running, and it would be nice to be able to take good pictures of them.")],
  [("to practise (UK) / practice (US)", "praticare"), ("to join a club", "iscriversi a una società"), ("to train", "allenarsi"),
   ("a black belt", "cintura nera"), ("to clear your mind", "svuotare la testa"), ("to keep fit", "tenersi in forma")],
  [("I do running.", "I go running. / I run.", "Sport in -ing con “go”: go running, go swimming, go skiing.", "calque"),
   ("I practise judo since I was a child.", "I've practised judo since I was a child.", "Da allora a oggi → present perfect.", "tense"),
   ("In the free time I read.", "In my free time I read.", "Con “free time” si usa il possessivo.", "art")],
  ["How much free time do you have during the week?", "What did you do last weekend?", "Is sport important for children? Why?", "Do you watch sport on TV?"]),

topic("p1-home", "1.8", "Casa e quartiere", "Dove vivi, la tua casa, i vicini",
  ["home", "town", "family"], 7,
  "Descrivere il posto dove vivi con preposizioni di luogo corrette.",
  [("Where do you live?",
    "I live in Brugnera, a small town in the province of Pordenone, in the north-east of Italy. It's a quiet place near the Livenza river, about an hour's drive from Venice."),
   ("What do you like about the area where you live?",
    "I like the fact that it's peaceful and green. There are lots of paths along the river where I can go running. On the other hand, you need a car for almost everything, because public transport is quite limited."),
   ("Describe your home.",
    "I live in a detached house with a small garden. It was built in 2007, so it's fairly modern. My favourite room is the living room, because it's bright and it's where the family spends most of the time."),
   ("Have you ever lived in another town?",
    "No, I haven't. I've always lived in this area. I've thought about moving to a bigger city a few times, but in the end I've always stayed, mainly because my family and friends are here."),
   ("Would you like to change anything about your neighbourhood?",
    "I'd like more services for young people, like a sports centre or a library that's open in the evening. At the moment, teenagers have to go to Pordenone if they want to do something.")],
  [("a detached / semi-detached house", "casa singola / bifamiliare"), ("a flat (UK) / an apartment (US)", "appartamento"),
   ("the outskirts", "la periferia"), ("a neighbourhood", "quartiere / zona"), ("peaceful", "tranquillo"),
   ("an hour's drive from", "a un'ora di macchina da")],
  [("I live in a little town near to Pordenone.", "I live in a small town near Pordenone.", "“Near” senza “to”; per le città si preferisce “small”.", "prep"),
   ("In my house there is a garden.", "My house has a garden. / There's a garden at my house.", "Il calco “in my house there is” si capisce, ma suona italiano.", "calque"),
   ("I live here from 20 years.", "I've lived here for 20 years.", "“Da 20 anni” = present perfect + for.", "tense")],
  ["What's your favourite room at home? Why?", "Do you know your neighbours well?", "Would you prefer to live in the city centre?", "What's the best thing about your town?"]),

topic("p1-tech", "1.9", "Tecnologia e internet", "Uso quotidiano, vantaggi, rischi",
  ["tech", "education", "work"], 11,
  "Esprimere opinioni bilanciate (vantaggi / svantaggi) sulla tecnologia.",
  [("How important is technology in your life?",
    "Very important, both at work and at home. I teach electronics, so technology is literally my job. But I try not to depend on it too much in my free time."),
   ("What piece of technology couldn't you live without?",
    "Probably my laptop. I use it to prepare lessons, correct tests and keep in touch with colleagues. My smartphone is important too, but I could manage without it for a few days."),
   ("Do you think technology makes people's lives better?",
    "In most ways, yes. It saves us time and gives us access to information. However, it can also make us more isolated, and I think many people find it difficult to switch off."),
   ("How do you use the internet for learning?",
    "A lot. I watch tutorials when I need to learn something practical, and at the moment I'm using an app to practise my English speaking. I think it's great that you can learn almost anything online for free."),
   ("Should children use technology at school?",
    "Yes, but with limits. Students need to learn how to use computers properly, because they'll need them for work. But I still think they should write by hand and read real books, too.")],
  [("to switch off", "staccare (anche mentalmente)"), ("to keep in touch with", "restare in contatto con"),
   ("a device", "un dispositivo"), ("to download / upload", "scaricare / caricare"),
   ("tech-savvy", "esperto di tecnologia"), ("screen time", "tempo davanti agli schermi")],
  [("The technology is important.", "Technology is important.", "Concetto generale → niente articolo.", "art"),
   ("I use internet every day.", "I use the internet every day.", "“The internet” vuole l'articolo.", "art"),
   ("It depends from the situation.", "It depends on the situation.", "Depend <strong>on</strong>, mai “from”.", "prep")],
  ["What was the last thing you bought online?", "Do you think we spend too much time on screens?", "Which app do you use most?", "How will technology change schools in the future?"]),

topic("p1-shopping", "1.10", "Acquisti e soldi", "Negozi, online, risparmiare",
  ["shopping", "tech"], 11,
  "Confrontare negozi e acquisti online con strutture comparative corrette.",
  [("Do you enjoy shopping?",
    "Not really, to be honest. I only go shopping when I need something. I'm the kind of person who knows what he wants, goes in, buys it and leaves as quickly as possible."),
   ("Do you prefer shopping online or in shops?",
    "It depends on what I'm buying. For clothes and shoes I prefer going to a shop, because I want to try them on. For books or electronic components I usually order online, because it's cheaper and quicker."),
   ("What was the last thing you bought?",
    "The last thing I bought was a new pair of running shoes. My old ones were completely worn out. I went to a sports shop so that the assistant could check the way I run."),
   ("Is it easy to save money these days?",
    "No, it isn't. Prices have gone up a lot in the last few years, especially energy and food. I try to save a bit every month, but it's harder than it used to be."),
   ("Have you ever bought something you regretted?",
    "Yes, I have. A few years ago I bought an expensive exercise bike because I was sure I would use it every day. I used it about five times and then it became a place to hang clothes!")],
  [("to try something on", "provare (un vestito)"), ("worn out", "consumato"), ("a bargain", "un affare"),
   ("the sales", "i saldi"), ("to go up / to rise", "aumentare (prezzi)"), ("a receipt", "scontrino / ricevuta")],
  [("Online is more cheap.", "Online it's cheaper.", "Comparativo breve: cheap → cheaper.", ""),
   ("I bought a new shoes.", "I bought a new pair of shoes.", "“Shoes” è plurale: niente “a”.", "art"),
   ("The prices are increased.", "Prices have gone up. / Prices have increased.", "Calco del passivo italiano “sono aumentati”.", "calque")],
  ["Where do you usually buy your clothes?", "Do you like giving presents?", "Is money important for happiness?", "Did you get pocket money as a child?"]),

topic("p1-weather", "1.11", "Tempo atmosferico e stagioni", "Stagioni, clima, attività all'aperto",
  ["weather", "environment", "freetime"], 7,
  "Parlare del tempo e delle stagioni collegandoli alle tue abitudini.",
  [("What's your favourite season?",
    "Autumn, I think. It isn't too hot or too cold, which is perfect for running, and the colours of the trees are beautiful. I also like the food: chestnuts, mushrooms and new wine!"),
   ("What's the weather usually like where you live?",
    "It's quite humid. The summers are hot and sticky, and in winter we often have fog, especially in the morning. It doesn't snow much in the plain, but the mountains are only an hour away."),
   ("Does the weather affect your mood?",
    "Yes, it does. When it's grey and rainy for days, I feel more tired and less motivated. On the other hand, a sunny morning always puts me in a good mood."),
   ("Has the weather changed in your area in recent years?",
    "Yes, a lot. Summers have become much hotter and there have been more extreme storms. A few years ago we had a terrible hailstorm that damaged lots of cars and roofs in my town.",
    "<em>have become / have been</em> (cambiamento fino a oggi) poi <em>we had</em> (evento con data)."),
   ("What do you like doing when it rains?",
    "I usually stay at home and read, or I catch up on work. If I really need to move, I go to the gym instead of running outside.")],
  [("humid / sticky", "umido / afoso"), ("fog / foggy", "nebbia / nebbioso"), ("a hailstorm", "grandinata"),
   ("it's pouring (with rain)", "piove a dirotto"), ("mild", "mite"), ("to put someone in a good mood", "mettere di buon umore")],
  [("It makes very hot in summer.", "It's very hot in summer.", "Calco di “fa caldo”: in inglese “it is”.", "calque"),
   ("In the winter there is a lot of fog.", "In winter there's a lot of fog.", "Le stagioni in generale: di solito senza “the”.", "art"),
   ("The weather is changed.", "The weather has changed.", "Calco di “è cambiato”: serve “has”.", "tense")],
  ["What do you do on hot summer days?", "Do you check the weather forecast every day?", "Would you like to live in a hotter or colder country?", "What was the weather like last weekend?"]),

topic("p1-family", "1.12", "Famiglia e amici", "Relazioni, tempo insieme, amicizia",
  ["family", "freetime"], 11,
  "Descrivere persone e relazioni senza errori di pronomi e possessivi.",
  [("Tell me about your family.",
    "It's a fairly small family. My parents still live nearby, so I see them almost every week. I have a brother who lives in another city; we don't see each other often, but we speak on the phone regularly."),
   ("Who are you closest to in your family?",
    "Probably my mother. She's a very practical person and she always gives me good advice, even if I don't always follow it!"),
   ("How often do you see your friends?",
    "Not as often as I'd like. Most of my friends have busy lives, like me. We usually meet up once or twice a month for dinner, and I see some of them at the judo club."),
   ("What makes a good friend?",
    "For me, a good friend is someone you can rely on, who tells you the truth even when it's not what you want to hear. I also think it's important to have fun together."),
   ("How did you meet your best friend?",
    "We met at secondary school. We sat next to each other in the lab on the first day, and we became friends almost immediately. We've known each other for more than thirty years now.",
    "<em>We met</em> (quando) e <em>we've known each other for</em> (da quanto tempo).")],
  [("to rely on", "contare su"), ("to get on well with", "andare d'accordo con"), ("to meet up", "vedersi (con amici)"),
   ("close to", "legato a"), ("relatives", "parenti"), ("to grow up", "crescere")],
  [("My parents are my relatives more close.", "My parents are my closest relatives.", "Superlativo breve: close → closest.", ""),
   ("I know him since 30 years.", "I've known him for 30 years.", "“Conosco da” = present perfect + for.", "tense"),
   ("She gives me good advices.", "She gives me good advice.", "“Advice” non è numerabile: niente -s.", "vocab")],
  ["Do you come from a big family?", "Is it easy to make friends as an adult?", "What do you usually do with your family at weekends?", "Do you keep in touch with old school friends?"]),

topic("p1-health", "1.13", "Salute e stile di vita", "Abitudini sane, stress, sonno",
  ["health", "sport", "food"], 11,
  "Dare consigli e parlare di abitudini con should, try to, used to.",
  [("What do you do to stay healthy?",
    "I try to stay active: I go running and I do judo. I also try to eat well, although I'm not always strict about it. The thing I find hardest is getting enough sleep during the school year."),
   ("Do you think people today are healthier than in the past?",
    "In some ways, yes: we know more about nutrition and medicine is much better. But people also spend more time sitting down, and stress is a big problem, especially at work."),
   ("How do you deal with stress?",
    "Exercise is the best solution for me. After a run or a judo session I always feel calmer. I also try not to check work emails in the evening, although it's not always easy."),
   ("Have you changed any habits recently to be healthier?",
    "Yes, I have. I've started going to bed earlier, and I've stopped drinking coffee after lunch. I've noticed that I sleep much better now."),
   ("What advice would you give to someone who wants to get fit?",
    "I'd tell them to start slowly and choose an activity they actually enjoy. If you hate the gym, you won't go. It's better to walk for thirty minutes every day than to train hard once a month.")],
  [("to get fit / to keep fit", "rimettersi / tenersi in forma"), ("to deal with", "gestire / affrontare"),
   ("a habit", "un'abitudine"), ("to take up (a sport)", "iniziare (uno sport)"), ("a sedentary lifestyle", "vita sedentaria"),
   ("to give up (smoking)", "smettere di (fumare)")],
  [("I try to make sport every day.", "I try to do some exercise every day.", "Si “does” sport/exercise, non si “make”.", "calque"),
   ("I have stopped to drink coffee.", "I've stopped drinking coffee.", "Stop + -ing = smettere di fare; stop + to = fermarsi per fare.", ""),
   ("The stress is a big problem.", "Stress is a big problem.", "Sostantivo astratto in generale: niente “the”.", "art")],
  ["How many hours do you usually sleep?", "Is it expensive to live a healthy life?", "Should the government do more to keep people healthy?", "What's the healthiest thing you did last week?"]),

topic("p1-festivals", "1.14", "Feste e celebrazioni", "Natale, compleanni, tradizioni locali",
  ["festivals", "family", "food"], 7,
  "Descrivere una tradizione e raccontare una festa passata.",
  [("What's the most important celebration in your country?",
    "I'd say Christmas. It's a time when families get together, usually for a very long lunch on Christmas Day. In my region we also celebrate Epiphany, on the sixth of January, with big bonfires called “pignarûl”."),
   ("How did you celebrate your last birthday?",
    "Nothing special, to be honest. I had dinner with my family at home, and my colleagues brought a cake to school. I'm not a big fan of parties, so that was perfect for me."),
   ("Do you prefer big parties or small gatherings?",
    "Small gatherings, definitely. I prefer spending time with a few close friends, where you can actually talk to people. At big parties it's often too noisy to have a real conversation."),
   ("Is there a local festival in your area?",
    "Yes, several. In many towns there are summer festivals called “sagre”, where volunteers cook local food and there's live music. They're a great way to meet people and support local associations."),
   ("Have traditions changed since you were young?",
    "Yes, a bit. Some traditions have become more commercial, like Halloween, which we didn't celebrate at all when I was a child. But the family meals at Christmas are still the same.")],
  [("to get together", "riunirsi"), ("a bonfire", "falò"), ("a gathering", "ritrovo / riunione"),
   ("a volunteer", "volontario"), ("to celebrate", "festeggiare"), ("Christmas Eve / Day", "vigilia / giorno di Natale")],
  [("At Christmas we make a big lunch.", "At Christmas we have a big lunch.", "Il pasto: have, non make (a meno che tu non lo cucini).", "calque"),
   ("In the 6 January.", "On the sixth of January.", "Date e giorni: <strong>on</strong>.", "prep"),
   ("I have celebrated my birthday last week.", "I celebrated my birthday last week.", "“Last week” → past simple.", "tense")],
  ["What do you usually do on New Year's Eve?", "Do you give presents at Christmas?", "Which festival from another country would you like to see?", "What's the best party you've ever been to?"]),

topic("p1-media", "1.15", "Media, notizie, film", "Come ti informi, cosa guardi e leggi",
  ["media", "tech", "freetime"], 3,
  "Parlare di notizie, film e libri dando opinioni e motivazioni.",
  [("How do you usually get the news?",
    "Mostly online. I read a couple of news websites in the morning, and I listen to the radio in the car on the way to school. I rarely buy a newspaper these days."),
   ("Do you trust the news you read on social media?",
    "Not really. There's a lot of fake news on social media, so if I read something surprising, I try to check it on a reliable website before I believe it."),
   ("What kind of films do you like?",
    "I like thrillers and science fiction, because they keep you thinking. I'm not a big fan of romantic comedies. The last film I saw was a documentary about space exploration, and it was fascinating."),
   ("Do you prefer reading books or watching films?",
    "It depends on how tired I am! In the evening, after a long day, I usually watch something. But on holiday I love reading, and I often think the book is better than the film."),
   ("Tell me about a TV programme you enjoyed recently.",
    "Recently I watched a series about the history of engineering, how big bridges and tunnels were built. I enjoyed it because it's connected to my job and I learnt a lot of things I can tell my students.")],
  [("fake news", "notizie false"), ("reliable", "affidabile"), ("a series (sing. e pl.)", "una serie TV"),
   ("a documentary", "documentario"), ("headlines", "titoli (dei giornali)"), ("to keep up with the news", "tenersi aggiornato")],
  [("I have seen a film yesterday.", "I saw a film yesterday.", "“Yesterday” → past simple.", "tense"),
   ("The news are bad.", "The news is bad.", "“News” è singolare.", "vocab"),
   ("I informate myself on internet.", "I keep up with the news online.", "“Informate” non esiste; “online” evita anche il problema dell'articolo.", "calque")],
  ["Do you listen to podcasts?", "What was the last book you read?", "Do you think newspapers will disappear?", "Do you prefer watching films at home or at the cinema?"]),

topic("p1-environment", "1.16", "Ambiente e natura", "Riciclo, clima, piccoli gesti",
  ["environment", "weather", "town"], 11,
  "Esprimere opinioni sull'ambiente senza restare nel vago: fatti concreti della tua vita.",
  [("Do you do anything to help the environment?",
    "I try to. We recycle everything at home, because in my town the collection is very strict. I also try to use the car less, and in summer I sometimes cycle to school."),
   ("Is there a lot of pollution where you live?",
    "Quite a lot, unfortunately. The Po Valley is one of the most polluted areas in Europe, especially in winter, because the mountains block the wind. On some days the air quality is really bad."),
   ("Do you spend much time in nature?",
    "Yes, quite a lot, mostly when I go running. There's a beautiful path along the river near my house. At the weekend we sometimes go hiking in the mountains, which are only an hour away."),
   ("Who should do more to protect the environment: governments or individuals?",
    "Both, but I think governments and big companies have the biggest responsibility, because their decisions have a much larger impact. Individuals can help, but they need good public transport and clear rules."),
   ("Have you changed anything in your life for environmental reasons?",
    "Yes. A few years ago we installed solar panels on the roof, and I've stopped buying plastic bottles. It's not much, but I think small changes add up.")],
  [("to recycle / recycling", "riciclare / raccolta differenziata"), ("pollution / polluted", "inquinamento / inquinato"),
   ("solar panels", "pannelli solari"), ("to add up", "sommarsi, fare la differenza"),
   ("waste", "rifiuti / spreco"), ("to reduce your carbon footprint", "ridurre l'impronta di CO₂")],
  [("I make the differentiated collection.", "I recycle. / I separate my rubbish.", "Calco diretto: in inglese si dice semplicemente “recycle”.", "calque"),
   ("The nature is important.", "Nature is important.", "Nature in generale: niente “the”.", "art"),
   ("We have installed solar panels two years ago.", "We installed solar panels two years ago.", "“Two years ago” → past simple.", "tense")],
  ["What's the biggest environmental problem in your area?", "Would you buy an electric car?", "Should plastic bags be banned?", "Do young people care more about the environment?"]),
]
