from _h import *


def rp(id, n, title, sub, tags, day, goal, phrases, d1, d2, drills, fix=None):
    """d1 = (contesto, righe) con l'esaminatore che inizia; d2 = (contesto, righe) con te che inizi."""
    blocks = [PH(phrases),
              DLG(d1[1], h="Role-play A · inizia l'esaminatore", ctx=d1[0]),
              DLG(d2[1], h="Role-play B · inizi tu", ctx=d2[0])]
    if fix:
        blocks.append(FIX(fix))
    blocks.append(TASK("<p>Leggi la situazione, pensa 10 secondi, poi recita <em>entrambe</em> le parti ad alta voce (o chiedi a qualcuno di fare l'esaminatore). Ogni role-play dura circa 90 secondi.</p><ol>" +
                       "".join(f"<li>{d}</li>" for d in drills) + "</ol>", 90, 10))
    return L(id, n, title, sub, tags, 15, day, goal, *blocks)


E, Y = "Examiner", "You"

LESSONS = [
L("p2-howto", "2.0", "Come funziona la Part 2", "Due mini-dialoghi: reagire e iniziare",
  ["functions", "strategy", "format"], 10, 4,
  "Capire il meccanismo dei role-play e la regola dei 3 passi: reagisci, sviluppa, chiudi.",
  P("""<p>L'esaminatore legge una situazione breve: <em>“I'm your neighbour. You're going to have a party on Saturday. Tell me about it.”</em> oppure <em>“I'm your colleague. I'll start.”</em>. Ogni role-play dura circa un minuto e mezzo, con 3–4 battute a testa.</p>
<p>La Part 2 non valuta cosa dici, ma <strong>se usi la funzione giusta</strong> (scusarti, proporre, lamentarti…) con il registro adatto: cortese ma naturale.</p>"""),
  UL(["<strong>1. Reagisci</strong> alla situazione con la frase funzionale giusta (<em>I'm so sorry…</em>, <em>Congratulations!</em>, <em>Could you possibly…?</em>).",
      "<strong>2. Sviluppa</strong>: dai un motivo, una proposta concreta o una domanda. È qui che mostri il livello B2.",
      "<strong>3. Chiudi</strong> o rilancia: <em>Does that sound OK?</em> · <em>Let me know.</em> · <em>Thanks again.</em>"],
     h="La regola dei 3 passi"),
  FIX([("I'm sorry for the delay, I have had a problem with the car.", "Sorry I'm late — I had a problem with the car.", "Il problema è finito: past simple. E “sorry I'm late” è più naturale.", "tense"),
       ("You must come to my party!", "You should come to my party! / I'd love you to come.", "“Must” suona come un ordine. Usa forme più morbide.", ""),
       ("Can you give me the salt?", "Could you pass me the salt, please?", "Con persone che non conosci bene: “could” + “please”.", "")]),
  TASK("<p>Per ogni situazione, di' <em>solo la prima battuta</em> con i 3 passi (reazione + sviluppo + domanda):<br>1. Your friend tells you they've just got engaged.<br>2. You need to leave a meeting early.<br>3. A colleague offers to help you move house.</p>", 60),
),

L("p2-phrases", "2.1", "Kit di frasi funzionali", "Proporre, scusarsi, rassicurare, chiedere e altro",
  ["functions", "fluency"], 20, 4,
  "Avere in bocca, senza pensarci, 2–3 frasi per ogni funzione della Part 2.",
  P("""<p>Questa è la lezione da ripassare più spesso. Non serve impararle tutte: scegline <strong>due per gruppo</strong> e usale finché diventano automatiche. Premi <em>ascolta</em> per sentire l'intonazione.</p>"""),
  PH([("Proporre / suggerire", [("Why don't we…?", ""), ("How about + -ing…?", "How about going by train?"), ("What if we…?", ""), ("Shall I…?", "offrirsi"), ("It might be a good idea to…", "")]),
      ("Scusarsi", [("I'm really sorry about…", ""), ("I'm so sorry, I completely forgot.", ""), ("I feel terrible about it.", ""), ("It won't happen again, I promise.", "")]),
      ("Rassicurare / accettare le scuse", [("Don't worry about it.", ""), ("It's not a big deal.", ""), ("These things happen.", ""), ("No harm done.", "nessun danno")]),
      ("Chiedere un favore / un permesso", [("Could you possibly…?", "molto cortese"), ("Would you mind + -ing…?", "Would you mind lending me…?"), ("Is it OK if I…?", ""), ("I was wondering if you could…", "il più cortese")]),
      ("Rispondere a un favore", [("Sure, no problem.", ""), ("Of course, go ahead.", ""), ("I'd like to help, but…", "rifiutare con gentilezza"), ("I'm afraid I can't, because…", "")]),
      ("Invitare / accettare / rifiutare", [("Would you like to come to…?", ""), ("I'd love to, thanks!", ""), ("That sounds great!", ""), ("I'd love to, but I'm afraid I've already got plans.", "")]),
      ("Lamentarsi con cortesia", [("I'm afraid there's a problem with…", ""), ("I'm sorry to bother you, but…", ""), ("I'd like to make a complaint about…", "formale"), ("Would it be possible to…?", "chiedere una soluzione")]),
      ("Consigliare", [("If I were you, I'd…", ""), ("You should / You could…", ""), ("Have you thought about + -ing…?", ""), ("It's worth + -ing…", "vale la pena")]),
      ("Congratularsi / consolare", [("Congratulations! That's fantastic news!", ""), ("Well done, you deserve it.", ""), ("Oh no, I'm sorry to hear that.", ""), ("That must be really hard for you.", "")]),
      ("Ringraziare e chiudere", [("Thanks a lot, I really appreciate it.", ""), ("That's really kind of you.", ""), ("Let me know if you need anything.", ""), ("See you then!", "")])],
     h="Le frasi, per funzione"),
  FIX([("Would you mind to lend me your car?", "Would you mind lending me your car?", "Would you mind + -ing.", ""),
       ("How about to go to the cinema?", "How about going to the cinema?", "How about + -ing.", ""),
       ("If I would be you, I would…", "If I were you, I'd…", "Nella frase con if: “were”, non “would be”.", "")]),
  TASK("<p>Timer di 2 minuti: per ogni gruppo di frasi qui sopra, inventa ad alta voce una frase completa su una situazione della tua scuola o della palestra di judo.</p>", 120),
),

rp("p2-apologise", "2.2", "Scusarsi e rassicurare", "Ritardi, danni, dimenticanze",
  ["functions", "work", "manners"], 4,
  "Scusarti in modo credibile (scusa + motivo + rimedio) e accettare le scuse degli altri.",
  [("Scusarsi bene: scusa + motivo + rimedio", [("I'm really sorry I'm late. The traffic was terrible.", ""), ("Let me make it up to you.", "lascia che mi faccia perdonare"), ("I'll pay for the repair, of course.", "")]),
   ("Accettare le scuse", [("Honestly, don't worry about it.", ""), ("It could happen to anyone.", ""), ("Never mind, we can sort it out.", "")])],
  ("I'm your colleague. You borrowed my laptop charger yesterday and you've lost it. I'll start.",
   [(E, "Hi! Have you still got my charger? I need it for the meeting this afternoon."),
    (Y, "Oh, I'm really sorry, I'm afraid I've lost it. I'm sure I left it in the lab, but it isn't there any more."),
    (E, "Oh no. That's a problem — my battery is almost dead."),
    (Y, "I feel terrible about it. Look, why don't you use my laptop for the meeting? And I'll buy you a new charger today, I promise."),
    (E, "Well, OK, that would help. Thanks."),
    (Y, "It's the least I can do. Again, I'm really sorry.")]),
  ("I'm your friend. You were supposed to meet me for dinner last night, but you forgot. You start.",
   [(Y, "Hi Marco, listen, I'm so sorry about last night. I completely forgot about our dinner."),
    (E, "Yes, I waited for half an hour at the restaurant!"),
    (Y, "I know, I feel awful. I had a really busy day at school and it went out of my head. Let me make it up to you — dinner's on me this weekend. How about Saturday?"),
    (E, "Hmm, Saturday could work."),
    (Y, "Great. I'll book the table this time, and I'll set a reminder on my phone!")]),
  ["I'm your neighbour. Your dog has damaged my garden. I'll start.",
   "You broke a friend's favourite mug when you were at their house. You start.",
   "I'm your manager. You missed an important deadline. I'll start."],
  fix=[("Sorry for arriving late.", "Sorry I'm late.", "Più naturale e diretto nel parlato.", "calque"),
       ("I have forgotten our appointment yesterday.", "I forgot our appointment yesterday.", "“Yesterday” → past simple.", "tense")]),

rp("p2-invite", "2.3", "Invitare, accettare, rifiutare", "Feste, uscite, eventi",
  ["functions", "freetime", "family"], 5,
  "Invitare in modo concreto (quando, dove, cosa) e rifiutare senza sembrare scortese.",
  [("Invitare", [("I'm having a few friends over on Saturday. Would you like to come?", ""), ("Are you free on Friday evening?", ""), ("It'd be great if you could make it.", "")]),
   ("Rifiutare con gentilezza", [("Thanks for asking, but I'm afraid I can't make it.", ""), ("I'd love to, but I've already promised…", ""), ("Can I take a rain check?", "rimandiamo a un'altra volta")])],
  ("I'm your colleague. I'm inviting you to my birthday party on Saturday. I'll start.",
   [(E, "I'm having a birthday party on Saturday night at my place. Would you like to come?"),
    (Y, "Oh, thanks for inviting me! I'd love to, but I'm afraid I've got a judo competition on Saturday and I usually get home really late."),
    (E, "Oh, what a shame. Are you sure you can't come, even for an hour?"),
    (Y, "Well, maybe I could come by after the competition, around ten. Would that be too late?"),
    (E, "Not at all, the party won't finish before midnight!"),
    (Y, "Perfect, then I'll try. Shall I bring anything? Some drinks, maybe?")]),
  ("You want to invite a friend to watch a basketball match with you next week. You start.",
   [(Y, "Hi Laura, are you free next Thursday evening? I've got two tickets for the basketball match in Trieste."),
    (E, "Oh, I'm not really into basketball…"),
    (Y, "I know, but the atmosphere is amazing, even if you don't follow the sport. We could have dinner in town before the match."),
    (E, "Dinner sounds good. What time would we leave?"),
    (Y, "Around six. I can pick you up, so you don't have to drive. What do you think?"),
    (E, "OK, why not? Count me in.")]),
  ["I'm your friend. I'm inviting you to go camping next weekend, but you hate camping. I'll start.",
   "You want to invite your colleagues to a small dinner at your house to celebrate the end of the school year. You start.",
   "I'm your cousin. I'm inviting you to my wedding, but it's the same day as your exam. I'll start."]),

rp("p2-complain", "2.4", "Lamentarsi con cortesia", "Ristoranti, hotel, vicini, negozi",
  ["functions", "shopping", "home"], 5,
  "Lamentarsi in modo fermo ma educato e chiedere una soluzione concreta.",
  [("Aprire il reclamo", [("Excuse me, I'm sorry to bother you, but…", ""), ("I'm afraid there's a problem with my room.", ""), ("I'm not very happy with…", "")]),
   ("Chiedere una soluzione", [("Would it be possible to change it?", ""), ("Could you do something about it, please?", ""), ("I'd like a refund, please.", "rimborso"), ("I'd appreciate it if you could…", "")])],
  ("I'm a hotel receptionist. You're a guest and you come to reception. I'll start.",
   [(E, "Good evening. How can I help you?"),
    (Y, "Good evening. I'm sorry to bother you, but I'm afraid there's a problem with my room. The air conditioning isn't working and it's really hot."),
    (E, "Oh, I'm sorry about that. I can send someone to look at it tomorrow morning."),
    (Y, "Tomorrow morning? I'm afraid that's a bit late — I won't be able to sleep tonight. Would it be possible to move to another room?"),
    (E, "Let me check… Yes, we have a room on the third floor."),
    (Y, "That would be great, thank you. I really appreciate it.")]),
  ("Your neighbour plays loud music every night until very late. You start.",
   [(Y, "Hi, sorry to bother you. Have you got a minute? It's about the music in the evening."),
    (E, "Oh, is it too loud?"),
    (Y, "Well, a little. It's fine during the day, but I have to get up at six for work, and at midnight it's still quite loud."),
    (E, "I'm sorry, I didn't realise you could hear it so well."),
    (Y, "Don't worry, I'm sure you didn't mean to. Would it be possible to turn it down after eleven, maybe?"),
    (E, "Of course, no problem."),
    (Y, "Thanks a lot, I really appreciate it.")]),
  ["I'm a waiter. You ordered a vegetarian dish, but it has meat in it. I'll start.",
   "You bought a pair of headphones last week and one side has stopped working. You go back to the shop. You start.",
   "I'm your flatmate. I never clean the kitchen. You start."],
  fix=[("I want to speak with the responsible.", "I'd like to speak to the manager, please.", "“Il responsabile” = the manager / the person in charge.", "calque"),
       ("The air conditioner doesn't work since yesterday.", "The air conditioning hasn't worked since yesterday.", "Da ieri fino ad ora → present perfect.", "tense")]),

rp("p2-request", "2.5", "Chiedere favori e permessi", "Prestiti, cambi di turno, aiuti",
  ["functions", "work", "family"], 7,
  "Chiedere qualcosa con le forme più cortesi e dare un motivo convincente.",
  [("Chiedere", [("I was wondering if you could help me with something.", ""), ("Would you mind swapping shifts with me on Friday?", ""), ("Is there any chance I could borrow your car?", "")]),
   ("Offrire qualcosa in cambio", [("I'd be happy to do the same for you.", ""), ("I owe you one!", "ti devo un favore"), ("I'll return it by Sunday, I promise.", "")])],
  ("I'm your neighbour. You are going on holiday and you need someone to water your plants. You start.",
   [(Y, "Hi, Anna. I was wondering if you could do me a favour."),
    (E, "Sure, what is it?"),
    (Y, "I'm going on holiday next week, and I need someone to water my plants. Would you mind doing it, maybe every two or three days?"),
    (E, "How long are you going to be away?"),
    (Y, "Just ten days. I can leave you the keys on Sunday. And of course I'd be happy to do the same for you when you go away."),
    (E, "No problem, I'll do it."),
    (Y, "Thanks so much, I owe you one!")]),
  ("I'm your colleague. I need you to cover my lesson tomorrow. I'll start.",
   [(E, "Hi, sorry, I need a big favour. Could you cover my lesson tomorrow at ten? I have a medical appointment."),
    (Y, "Tomorrow at ten… Let me check. I've got a free hour then, so yes, I think I can do it."),
    (E, "Oh, thank you so much."),
    (Y, "No problem. What class is it? And have you prepared something for them to do?"),
    (E, "It's 3B. I'll leave some exercises on the desk."),
    (Y, "Perfect. Just send me a message with the page numbers, so I'm ready.")]),
  ["You need to borrow a friend's car for the weekend because yours is at the mechanic's. You start.",
   "I'm your colleague. I'm asking you to lend me some money for lunch. I'll start.",
   "You want to leave work an hour early on Friday. Ask your head teacher. You start."]),

rp("p2-advice", "2.6", "Dare consigli e suggerire", "Amici in difficoltà, decisioni",
  ["functions", "education", "health"], 7,
  "Ascoltare il problema, mostrare empatia e dare 2 consigli concreti.",
  [("Mostrare empatia", [("That sounds really stressful.", ""), ("I know how you feel.", ""), ("I can see why you're worried.", "")]),
   ("Consigliare", [("If I were you, I'd talk to him directly.", ""), ("Have you thought about asking for help?", ""), ("Maybe you could try…", "morbido"), ("It might be worth + -ing…", "")])],
  ("I'm your friend. I have an important exam next week and I'm really stressed. I'll start.",
   [(E, "I've got my exam next week and I'm so stressed. I can't sleep and I can't concentrate."),
    (Y, "Oh, I know how you feel — I'm preparing for an exam too! Have you made a study plan?"),
    (E, "Not really, I just study whatever I can."),
    (Y, "If I were you, I'd write a plan for each day, with short breaks. It really helps. And maybe you could go for a walk or a run in the evening, to clear your mind."),
    (E, "That's a good idea. I haven't done any exercise for weeks."),
    (Y, "Try it, I'm sure you'll sleep better. And let me know if you want to study together one evening.")]),
  ("Your friend can't decide whether to accept a job in another city. You start.",
   [(Y, "So, have you decided about the job in Milan?"),
    (E, "No, I still don't know. The salary is much better, but my family is here."),
    (Y, "I can see why it's a difficult decision. Have you thought about asking them if you could work from home some days?"),
    (E, "No, I haven't. That's an interesting idea."),
    (Y, "It might be worth asking. That way you could spend long weekends here. Why don't you write down the pros and cons, too?")]),
  ["I'm your colleague. I want to get fit but I never have time. I'll start.",
   "Your friend's teenage son spends all day playing video games. Give some advice. You start.",
   "I'm your friend. I want to learn English but I don't know how to start. I'll start."],
  fix=[("I suggest you to talk to him.", "I suggest (that) you talk to him. / I suggest talking to him.", "Suggest non vuole “you to”.", "calque"),
       ("You should to rest.", "You should rest.", "Dopo should: verbo base, senza “to”.", "")]),

rp("p2-feelings", "2.7", "Congratularsi e consolare", "Buone e cattive notizie",
  ["functions", "family", "work"], 10,
  "Reagire con l'emozione giusta e fare una domanda di interesse.",
  [("Buone notizie", [("That's brilliant news! Congratulations!", ""), ("You must be so pleased!", ""), ("Well done — you really deserve it.", ""), ("We should celebrate!", "")]),
   ("Cattive notizie", [("Oh no, I'm so sorry to hear that.", ""), ("That's such a shame.", ""), ("Is there anything I can do?", ""), ("Try not to worry too much.", "")])],
  ("I'm your friend. I've just passed my driving test. I'll start.",
   [(E, "Guess what? I passed my driving test this morning!"),
    (Y, "That's brilliant news! Congratulations! You must be so pleased. Was it difficult?"),
    (E, "A bit. I was really nervous at the beginning."),
    (Y, "Well, you did it, that's what matters. Are you going to buy a car now?"),
    (E, "I hope so, a small second-hand one."),
    (Y, "Great! We should celebrate — let's go out for a pizza this weekend. You can drive!")]),
  ("Your colleague didn't get the promotion they were hoping for. You start.",
   [(Y, "Hi, I heard about the promotion. I'm really sorry, I know how much you wanted it."),
    (E, "Thanks. I'm quite disappointed, to be honest."),
    (Y, "Of course you are. It's such a shame, because everyone knows how hard you work."),
    (E, "Maybe next year."),
    (Y, "I'm sure there'll be other chances. And if you want to talk about it over a coffee, just let me know.")]),
  ["I'm your friend. My cat is very ill. I'll start.",
   "Your colleague has just become a grandfather. You start.",
   "I'm your cousin. I didn't get into the university I wanted. I'll start."],
  fix=[("I'm happy for you have passed.", "I'm really happy you passed!", "Struttura semplice: happy + frase.", ""),
       ("I'm sorry for your cat.", "I'm sorry to hear about your cat.", "“Sorry to hear about” è l'espressione naturale.", "prep")]),

rp("p2-plans", "2.8", "Organizzare e cambiare programmi", "Appuntamenti, spostamenti, disdette",
  ["functions", "events", "freetime"], 10,
  "Fissare, spostare o annullare un impegno proponendo un'alternativa concreta.",
  [("Fissare", [("What time suits you?", ""), ("Shall we say seven o'clock?", ""), ("Let's meet outside the station.", "")]),
   ("Spostare / annullare", [("I'm afraid something's come up.", "è saltato fuori un imprevisto"), ("Would it be OK if we met on Thursday instead?", ""), ("Could we move it to next week?", ""), ("I'll have to cancel, I'm really sorry.", "")])],
  ("I'm your friend. We planned to go to the cinema tonight, but I want to change the plan. I'll start.",
   [(E, "Hi, listen, about tonight — would you mind if we didn't go to the cinema? I'm really tired."),
    (Y, "No, of course not. Is everything OK?"),
    (E, "Yes, it's just been a long week."),
    (Y, "I understand. How about staying in and watching a film at your place instead? I could bring a pizza."),
    (E, "That sounds perfect."),
    (Y, "Great. Shall we say eight o'clock? Then you can relax a bit first.")]),
  ("You arranged to have lunch with a colleague tomorrow, but you have a meeting. You start.",
   [(Y, "Hi Paolo, I'm afraid something's come up for tomorrow. The head teacher has called a meeting at lunchtime."),
    (E, "Oh, never mind. These things happen."),
    (Y, "Thanks for understanding. Would it be OK if we had lunch on Thursday instead? Same place?"),
    (E, "Thursday's fine for me."),
    (Y, "Great, I'll book a table for one o'clock. See you then!")]),
  ["I'm your friend. We are organising a trip to the mountains. Decide when and where to meet. I'll start.",
   "You have to cancel a dentist's appointment. Phone the receptionist. You start.",
   "I'm your colleague. I want to move our project meeting to next week. I'll start."],
  fix=[("We can see us at seven?", "Shall we meet at seven? / Can we meet at seven?", "“Vederci” = meet. Niente “see us”.", "calque"),
       ("I have an appointment with the dentist tomorrow at 3.", "I've got a dentist's appointment at 3 tomorrow.", "“Dentist's appointment” è la forma naturale.", "vocab")]),

rp("p2-info", "2.9", "Chiedere informazioni", "Palestra, corsi, stazione, servizi",
  ["functions", "town", "travel", "phone"], 10,
  "Fare domande indirette e cortesi e chiedere chiarimenti.",
  [("Domande indirette (più cortesi)", [("Could you tell me what time the gym opens?", "non: what time does the gym open"), ("Do you know if there's a discount for teachers?", ""), ("I'd like to know how much the course costs.", "")]),
   ("Chiarire", [("Sorry, did you say fifteen or fifty?", ""), ("So, just to check, …", "riepilogare"), ("Could you spell that, please?", "")])],
  ("I'm a receptionist at a sports centre. You phone to ask about swimming courses. I'll start.",
   [(E, "Good morning, City Sports Centre. How can I help?"),
    (Y, "Good morning. I'm calling about your adult swimming courses. Could you tell me when they start?"),
    (E, "The next course starts on the fifteenth of October."),
    (Y, "Sorry, did you say the fifteenth or the fifth?"),
    (E, "The fifteenth. Tuesday and Thursday evenings."),
    (Y, "Great. And could you tell me how much it costs? Is there a discount if I sign up for the whole year?"),
    (E, "Yes, it's ten per cent off for the full year."),
    (Y, "Perfect. So, just to check: Tuesdays and Thursdays, from the fifteenth, with ten per cent off. Thank you very much.")]),
  ("You're at a train station in England. Ask for information about getting to the airport. You start.",
   [(Y, "Excuse me, could you tell me the quickest way to get to the airport?"),
    (E, "Sure. There's a direct train every thirty minutes from platform four."),
    (Y, "Do you know if I can buy the ticket on the train?"),
    (E, "You can, but it's more expensive. The machines are over there."),
    (Y, "Thanks. And how long does the journey take?"),
    (E, "About twenty-five minutes."),
    (Y, "Great, thanks for your help.")]),
  ["Phone a language school to ask about evening English courses. You start.",
   "I'm a tourist in your town. I'm asking you for a good restaurant. I'll start.",
   "You want to know the rules for bringing a bike on the train. Ask the ticket office. You start."],
  fix=[("Could you tell me what time does the gym open?", "Could you tell me what time the gym opens?", "Nella domanda indiretta l'ordine torna quello della frase affermativa.", "wo"),
       ("How much costs the course?", "How much does the course cost?", "Domanda diretta: serve “does”.", "wo")]),
]
