from _h import *


def task(id, n, title, sub, tags, day, goal, brief, you, exam, lines, focus, drill):
    return L(id, n, title, sub, tags, 20, day, goal,
             NEG(brief, you, exam),
             DLG(lines, h="Discussione modello (circa 3 minuti)"),
             UL(focus, h="Cosa notare nel modello"),
             TASK(drill, 210, 20, h="Ora tocca a te"))


E, Y = "Examiner", "You"

LESSONS = [
L("p3-howto", "3.0", "Come si vince la Part 3", "Valutare, confrontare, cedere, decidere",
  ["negotiation", "strategy", "format"], 10, 6,
  "Seguire uno schema in 4 fasi per arrivare a una decisione in 3–4 minuti, senza monologhi.",
  P("""<p>Tu e l'esaminatore avete un obiettivo comune (organizzare un evento, spendere un budget…) e due liste diverse. Non vince chi ha le idee migliori: vince chi <strong>interagisce</strong>, cioè ascolta, commenta le idee dell'altro, propone e arriva a un accordo.</p>"""),
  UL(["<strong>1. Apri e presenta (30″)</strong> — <em>So, we need to decide… I've got a few ideas. What about you?</em>",
      "<strong>2. Valuta le idee dell'altro (1′)</strong> — commenta almeno due sue idee, con un motivo: <em>That's a good idea because… / I'm not sure about…, because…</em>",
      "<strong>3. Confronta e negozia (1′30″)</strong> — <em>Your idea is cheaper, but mine would…</em> · proponi un compromesso: <em>What if we combined…?</em>",
      "<strong>4. Decidi e riassumi (30″)</strong> — <em>So, shall we go for…? · Great, so we've agreed on…</em>"],
     h="Le 4 fasi"),
  FIX([("I am agree with you.", "I agree with you.", "Errore classico: “agree” è un verbo.", "calque"),
       ("In my opinion I think that…", "In my opinion, … / I think…", "Doppione: scegli uno dei due.", "calque"),
       ("It's a good idea, but it costs too much money, it's far, and people don't like it, and…", "It's a good idea, but I'm worried about the cost.", "Un motivo chiaro vale più di una lista. Lascia spazio all'esaminatore.", "")]),
  TASK("<p>Senza compagno: prendi due idee qualsiasi (<em>a picnic</em> vs <em>a restaurant dinner</em>) e fai a voce alta le 4 fasi da solo, recitando anche le battute dell'esaminatore.</p>", 180),
),

L("p3-phrases", "3.1", "Frasi per negoziare", "Accordo, disaccordo, proposte, decisioni",
  ["negotiation", "connectors", "fluency"], 15, 6,
  "Avere 2 frasi pronte per ogni momento della negoziazione, dal più morbido al più deciso.",
  PH([("Aprire", [("So, we need to decide on…", ""), ("Shall I start? / Would you like to start?", ""), ("Let's look at the options.", "")]),
      ("Chiedere l'opinione dell'altro", [("What do you think about…?", ""), ("How do you feel about…?", ""), ("Which of your ideas do you like best?", "")]),
      ("Essere d'accordo", [("That's a great idea.", ""), ("I couldn't agree more.", "d'accordissimo"), ("Good point — I hadn't thought of that.", ""), ("Yes, and on top of that…", "aggiungere")]),
      ("Essere in parte d'accordo", [("I see what you mean, but…", ""), ("That's true, although…", ""), ("You've got a point, but have you considered…?", "")]),
      ("Non essere d'accordo (con garbo)", [("I'm not sure that's the best option, because…", ""), ("I'm afraid I don't really agree.", ""), ("I see your point, but I think… would work better.", ""), ("The problem with that is…", "")]),
      ("Proporre un compromesso", [("What if we combined the two ideas?", ""), ("How about a compromise? We could…", ""), ("Maybe we could do both, if…", ""), ("OK, I'm happy to go with your idea if we also…", "")]),
      ("Decidere e riassumere", [("So, shall we go for…?", ""), ("Are we agreed, then?", ""), ("So, to sum up, we've decided to…", "")])]),
  FIX([("I don't agree with you about this thing.", "I don't really agree with that.", "“This thing” = calco di “questa cosa”.", "calque"),
       ("According to me…", "In my view… / I think…", "“According to” si usa per gli altri, non per sé.", "calque"),
       ("We could make a party.", "We could have / throw a party.", "Una festa si “have” o “throw”.", "calque")]),
  TASK("<p>Rispondi a queste proposte dell'esaminatore usando <em>ogni volta</em> un gruppo diverso (accordo, accordo parziale, disaccordo, compromesso):<br>1. “Let's hire a famous chef.”<br>2. “I think we should do it on a Sunday.”<br>3. “We could ask each student to pay €20.”<br>4. “Why don't we invite the local newspaper?”</p>", 120),
),

task("p3-schoolday", "3.2", "Festa di fine anno a scuola", "Decidere come celebrare la fine dell'anno scolastico",
  ["negotiation", "events", "education"], 6,
  "Negoziare un evento scolastico commentando le idee dell'altro prima di proporre le tue.",
  "Your school wants to organise an event to celebrate the end of the school year. You have a budget of €1,500. Discuss the ideas and decide together on <strong>one</strong> event.",
  ["A trip to an amusement park", "A sports tournament with parents", "A concert with student bands"],
  ["A dinner in a local restaurant", "An exhibition of the students' projects", "A day at the beach"],
  [(E, "So, we need to decide how to celebrate the end of the school year. What ideas have you got?"),
   (Y, "Well, I was thinking about a sports tournament with parents, or a concert with student bands. But first, what are your ideas?"),
   (E, "I thought about an exhibition of the students' projects, or maybe a day at the beach."),
   (Y, "I really like the idea of an exhibition, because students could show what they've learnt during the year. The beach, on the other hand, might be difficult, because it's quite far and we'd need to pay for coaches."),
   (E, "That's true. But students love going to the beach at the end of the year."),
   (Y, "I see what you mean, but I think the transport would use up most of the budget. What if we combined the exhibition with the concert? In the afternoon, visitors could see the projects, and in the evening the student bands could play."),
   (E, "That's an interesting idea. Would parents come?"),
   (Y, "I think so, especially if their children are performing. And it would be cheap, because we could do it at school. We could spend the money on a sound system and some food."),
   (E, "OK, I'm convinced. So, shall we go for the exhibition and the concert?"),
   (Y, "Yes. So, to sum up, we've agreed on an exhibition in the afternoon and a concert in the evening, at school, with food for everyone.")],
  ["Chiede subito le idee dell'esaminatore (<em>But first, what are your ideas?</em>): interazione.",
   "Commenta due idee dell'altro con un motivo (<em>because… / might be difficult, because…</em>).",
   "Il disaccordo è morbido (<em>I see what you mean, but…</em>) e arriva con una proposta (<em>What if we combined…?</em>).",
   "Chiusura con riepilogo al present perfect: <em>we've agreed on…</em>"],
  "<p>Rifai la stessa discussione, ma questa volta prova a convincere l'esaminatore a scegliere la <em>gita al parco divertimenti</em>. Recita entrambe le parti oppure falla con Claude in modalità vocale.</p>"),

task("p3-teambuilding", "3.3", "Giornata di team building", "Un'attività per i colleghi",
  ["negotiation", "work", "events"], 7,
  "Proporre, obiettare e fare concessioni in un contesto di lavoro.",
  "Your company (or school) wants to organise a team-building day for 30 staff members to improve relationships between colleagues. Discuss the options and choose the best one.",
  ["A cooking class", "A hiking day in the mountains", "A volunteering day in the community"],
  ["An escape room", "A sailing trip", "A training workshop with a speaker"],
  [(E, "Right, we need to choose an activity for the team-building day. Would you like to start?"),
   (Y, "Sure. I think a hiking day in the mountains would be great, because people could talk while walking and enjoy the fresh air. What do you think?"),
   (E, "It sounds nice, but not everyone is fit enough for a long walk."),
   (Y, "Good point, I hadn't thought of that. We could choose an easy path, though. What about your ideas?"),
   (E, "I like the escape room. You really have to work together to get out."),
   (Y, "That's true, it's perfect for teamwork. The only problem is that most escape rooms are for groups of five or six, so we'd need to book several rooms, and people would be split up."),
   (E, "Hmm, you're right. What about the cooking class?"),
   (Y, "I like it a lot. Everybody can take part, it doesn't matter how fit you are, and at the end we eat together, which is the best way to get to know people."),
   (E, "OK, I agree. Although I'd still like something a bit more active."),
   (Y, "How about a compromise? We could do a short walk in the morning and the cooking class in the afternoon."),
   (E, "Perfect. Let's do that.")],
  ["Accetta l'obiezione (<em>Good point, I hadn't thought of that</em>) senza abbandonare l'idea.",
   "Critica l'idea dell'altro in modo costruttivo (<em>The only problem is that…</em>).",
   "Usa condizionali: <em>we'd need to…, people would be…</em>",
   "Il compromesso arriva quando l'esaminatore insiste."],
  "<p>Stesso compito, nuova regola: il budget è di soli €500. Quale attività diventa la migliore? Discutila in 3 minuti.</p>"),

task("p3-charity", "3.4", "Raccolta fondi benefica", "Raccogliere soldi per un'associazione locale",
  ["negotiation", "events", "town"], 10,
  "Confrontare vantaggi e svantaggi (costo, partecipazione, organizzazione) con comparativi corretti.",
  "Your town wants to raise money for the local hospital's children's ward. Discuss the ideas and decide which event would raise the most money.",
  ["A charity run", "A second-hand book sale", "A quiz night"],
  ["A dinner with a local celebrity", "A raffle with prizes from local shops", "A car wash organised by students"],
  [(E, "We need to raise money for the children's ward. Which idea do you like best?"),
   (Y, "Personally, I'd go for a charity run. Lots of people run these days, and each runner could pay an entry fee. How do you feel about that?"),
   (E, "It's a good idea, but organising a run is complicated. You need permission to close the roads."),
   (Y, "That's true, it's more complicated than the other options. What about your raffle idea? How would it work?"),
   (E, "Local shops donate prizes, and we sell tickets for five euros."),
   (Y, "I like it, because it's cheap to organise and shops get some publicity. But I'm not sure it would raise as much money as the run."),
   (E, "Maybe not, but more people would take part. Not everyone runs."),
   (Y, "You've got a point. What if we did both? We could sell raffle tickets at the finish line of the run, so people who come to watch can also help."),
   (E, "That's clever. Let's do that, and keep it simple: a short run in the park, so we don't need to close any roads."),
   (Y, "Great. So we've decided on a charity run in the park, with a raffle at the end.")],
  ["Comparativi: <em>more complicated than</em>, <em>as much money as</em>.",
   "Domanda di chiarimento sull'idea altrui (<em>How would it work?</em>): ottima interazione.",
   "L'esaminatore risolve il tuo problema e tu lo accetti: la decisione è davvero condivisa."],
  "<p>Stessa situazione: questa volta sostieni il <em>quiz night</em> e trova due motivi per cui è migliore della lotteria.</p>"),

task("p3-town", "3.5", "Il budget del comune per i giovani", "Come spendere €20.000 per i ragazzi",
  ["negotiation", "town", "freetime"], 10,
  "Sostenere un'opinione con esempi concreti e arrivare a una priorità.",
  "Your town council has €20,000 to spend on something for teenagers. Discuss the options and agree on the best way to spend the money.",
  ["A new skate park", "Free coding and robotics courses", "Longer opening hours for the library"],
  ["A youth centre with a café", "A free bus service on Saturday nights", "New equipment for the sports hall"],
  [(E, "So, how do you think we should spend the money?"),
   (Y, "I think free coding and robotics courses would be really useful, because they give young people skills for the future. I see it with my students — they love this kind of thing. What's your view?"),
   (E, "I think a youth centre would be better. Teenagers need somewhere to meet."),
   (Y, "I agree that they need a place to meet, that's a real problem in small towns. But €20,000 isn't enough to build and run a centre, is it?"),
   (E, "Maybe not a new building, but we could use an old one."),
   (Y, "That's a good point. In that case, we could hold the coding courses in the youth centre. Then it's not just a place to hang out, but also somewhere to learn."),
   (E, "I like that. And what about the Saturday night bus?"),
   (Y, "It's important for safety, but I think it would cost a lot every year, so it's not a one-off expense. Maybe the council could look at it next year."),
   (E, "Fair enough. So, the youth centre with courses?"),
   (Y, "Yes, let's go for that.")],
  ["Esempio personale (<em>I see it with my students</em>): rende l'opinione credibile.",
   "Question tag per coinvolgere: <em>isn't enough…, is it?</em>",
   "Rifiuto motivato di una terza idea (<em>it's not a one-off expense</em>)."],
  "<p>Riprova la discussione sostenendo lo <em>skate park</em>. Obiettivo: usa almeno 3 frasi diverse della lezione 3.1.</p>"),

task("p3-exchange", "3.6", "Accoglienza studenti stranieri", "Programma per un gruppo di studenti inglesi",
  ["negotiation", "education", "travel"], 11,
  "Pianificare un programma mettendo in ordine di priorità, con il futuro e i condizionali.",
  "A group of 20 British students is coming to your school for three days. Plan the programme together. You can choose <strong>three</strong> activities.",
  ["A guided tour of Venice", "A day in the school labs with Italian students", "A pizza-making workshop"],
  ["A visit to a local factory", "A hike in the Dolomites", "An evening with Italian families"],
  [(E, "We can only choose three activities. Where shall we start?"),
   (Y, "I think the most important thing is that they spend time with Italian students, so I'd definitely include a day in the labs. They could build a small project together."),
   (E, "Yes, I agree with that. I'd also include an evening with Italian families."),
   (Y, "That's a lovely idea. They'd see real Italian life, and it doesn't cost anything. So that's two. For the third one, I'd suggest Venice — they can't come all this way and not see it!"),
   (E, "Venice is beautiful, but it's very crowded and expensive. What about a visit to a local factory? There are some famous companies near here."),
   (Y, "Hmm, I see your point, and it would be interesting for technical students. But I think for teenagers Venice would be more memorable."),
   (E, "Maybe we could do the factory in the morning and a short walk in Venice in the afternoon?"),
   (Y, "That might be a bit tiring, but if the factory is on the way, why not? OK, let's go for that.")],
  ["Organizzazione chiara: <em>So that's two. For the third one…</em>",
   "Doppio ragionamento: riconosce il punto dell'altro e poi difende il suo (<em>I see your point… But…</em>).",
   "Accetta con condizione: <em>if the factory is on the way, why not?</em>"],
  "<p>Nuova versione: il gruppo resta solo un giorno e il budget è minimo. Scegli <em>una</em> attività con l'esaminatore.</p>"),

task("p3-club", "3.7", "L'anniversario della società sportiva", "Celebrare 50 anni di un club",
  ["negotiation", "sport", "events", "festivals"], 11,
  "Negoziare con lessico dello sport e degli eventi, mantenendo l'interazione.",
  "Your local sports club is celebrating its 50th anniversary. Discuss how to celebrate and choose the two best ideas.",
  ["An open day with free lessons for children", "A photo exhibition about the club's history", "A match against a famous team"],
  ["A gala dinner for members", "A club T-shirt for everyone", "A video with interviews with old members"],
  [(E, "Fifty years is a big anniversary. What do you think we should do?"),
   (Y, "I think an open day with free lessons for children would be perfect. It's a celebration, but it also brings new members to the club. What do you think?"),
   (E, "I like that. I also like the idea of a gala dinner for members."),
   (Y, "It would be nice, but it might be expensive, and not everyone would come. How about combining it with the history? We could make a video with interviews with old members and show it during a simple dinner at the club."),
   (E, "That's a great idea. People love seeing old photos and videos."),
   (Y, "Exactly. Some of the founders are still alive, so it would be really moving to hear their stories."),
   (E, "OK, so the open day and the dinner with the video?"),
   (Y, "Yes, I think that's the best combination: one event for the community and one for the members.")],
  ["Ogni idea ha uno scopo (<em>it also brings new members</em>): il “perché” è ciò che l'esaminatore vuole sentire.",
   "Chiusura con giustificazione finale: <em>one event for the community and one for the members</em>."],
  "<p>Immagina che sia il tuo club di judo. Rifai la discussione aggiungendo un'idea tua (per esempio un torneo o uno stage con un maestro famoso).</p>"),
]
