from _h import *


def mono(id, n, title, sub, tags, day, goal, topic, prompts, notes, model, follow, fix):
    return L(id, n, title, sub, tags, 20, day, goal,
             MONO(topic, prompts, notes, model, follow),
             FIX(fix, h="Attenzione a…"))


LESSONS = [
L("p4-structure", "4.0", "Lo schema del monologo", "Una storia semplice in 5 tappe",
  ["storytelling", "connectors", "tense", "strategy"], 15, 8,
  "Avere uno schema fisso che regge 2 minuti, così la testa pensa al contenuto e non alla struttura.",
  P("""<p>Nelle prove precedenti il problema della Part 4 era la <strong>coerenza</strong>: dettagli poco chiari o troppi. La soluzione è raccontare <em>una sola storia</em>, semplice, in 5 tappe. Ogni tappa dura circa 20–25 secondi.</p>"""),
  UL(["<strong>1. Introduzione</strong> — di cosa parli, in una frase. <em>I'd like to talk about my first judo teacher, who had a big influence on my life.</em>",
      "<strong>2. Contesto</strong> — quando, dove, chi (past simple / past continuous). <em>I met him when I was nine. I was a shy child and…</em>",
      "<strong>3. Il momento chiave</strong> — cosa è successo (past simple + connettori di sequenza). <em>One day… Then… Suddenly… In the end…</em>",
      "<strong>4. Come ti sei sentito / risultato</strong> — <em>I felt… · Thanks to that, I…</em>",
      "<strong>5. Riflessione oggi</strong> — perché conta ancora (present perfect / present simple). <em>Since then, I've always… · Looking back, I think…</em>"],
     h="Le 5 tappe"),
  PH([("Iniziare", [("I'd like to talk about…", ""), ("The person I've chosen is…", ""), ("This happened about ten years ago.", "")]),
      ("Sequenza", [("At first…", ""), ("After that… / Then…", ""), ("A few days later…", ""), ("In the end…", "alla fine (di una storia)"), ("Eventually…", "alla fine, dopo tempo/fatica")]),
      ("Aggiungere e contrastare", [("What's more…", ""), ("On top of that…", ""), ("However… / Even so…", ""), ("The funny thing is…", "")]),
      ("Chiudere", [("Looking back, I think…", ""), ("That's why… is so important to me.", ""), ("So, all in all…", ""), ("And that's how…", "")])],
     h="Connettori da parlato (non da tema scritto)"),
  FIX([("Moreover, furthermore, in addition…", "What's more… / Also… / On top of that…", "I connettori da scrittura suonano rigidi nel parlato: usa quelli colloquiali.", "conn"),
       ("I remember when I have met him.", "I remember when I met him.", "Un evento passato preciso → past simple.", "tense"),
       ("In the end of the story…", "At the end of the story… / In the end, …", "“At the end of” + qualcosa; “in the end” = alla fine, finalmente.", "prep")]),
  P("<p class=\"note\">Nei monologhi modello delle lezioni 4.2–4.8 persone ed episodi sono esempi costruiti su un insegnante di elettronica che fa judo e corre. Sostituiscili con le tue storie vere: si raccontano meglio.</p>"),
  TASK("<p>Usa le 5 tappe per raccontare <em>“the last time you learnt something new”</em>. Non preoccuparti del contenuto: conta di aver toccato tutte e 5 le tappe.</p>", 120, 30),
),

L("p4-notes", "4.1", "Appunti in 30 secondi", "Cosa scrivere (e cosa no) prima di parlare",
  ["storytelling", "strategy", "fluency"], 10, 8,
  "Usare i 30 secondi per decidere la storia, non per scrivere frasi.",
  P("""<p>In 30 secondi si scrivono <strong>5–7 parole chiave</strong>, una per tappa, più 2 connettori. Mai frasi intere: le leggeresti e perderesti fluidità.</p>
<p>Ordine delle decisioni: <strong>(1)</strong> scegli UNA storia concreta, la prima che viene in mente; <strong>(2)</strong> scrivi le 5 parole chiave; <strong>(3)</strong> scrivi in un angolo il tempo verbale principale (<em>PAST</em>) come promemoria.</p>""", h="Il metodo"),
  P("""<div class="split"><div class="sheet"><h3>Appunti che funzionano</h3><ul><li>judo teacher – Luciano</li><li>age 9, shy</li><li>1st competition – lost – his words</li><li>confidence ↑</li><li>now: my students</li><li><em>PAST · Looking back</em></li></ul></div>
<div class="sheet"><h3>Appunti che bloccano</h3><ul><li>“The person that I want to describe is my teacher of judo, because he…”</li><li>(frase lunga, tempo finito, e contiene due errori)</li></ul></div></div>""", h="Esempio"),
  FIX([("Scegliere l'esempio “migliore” e perdere 20 secondi.", "Scegli il primo esempio vero che ti viene in mente.", "Una storia vera si racconta meglio di una storia perfetta.", ""),
       ("Raccontare tre persone / tre viaggi.", "Una sola persona, un solo viaggio.", "Tre storie = dettagli confusi. Una storia = coerenza.", "")]),
  TASK("<p>Per ciascun argomento, scrivi gli appunti in 30 secondi (usa il timer). Non parlare: allena solo gli appunti.<br>1. A time you helped someone.<br>2. Your favourite place to relax.<br>3. A decision that changed your life.</p>", 30),
),

mono("p4-person", "4.2", "Una persona che ti ha influenzato", "Descrivere una persona e il suo impatto",
  ["storytelling", "sport", "family"], 8,
  "Descrivere una persona attraverso <em>un episodio</em>, non con una lista di aggettivi.",
  "Talk about a person who has had an important influence on your life.",
  ["Who is this person?", "How did you meet them?", "What did they do that influenced you?", "Why are they still important to you?"],
  ["judo teacher – Luciano", "age 9 – shy", "1st competition – lost – “you didn't lose, you learnt”", "confidence ↑, never stopped", "now: I say the same to my students", "PAST → Looking back"],
  ["I'd like to talk about my first judo teacher, Luciano, who probably had the biggest influence on my life after my parents.",
   "I met him when I was about nine. At that time I was a very shy child, and my parents thought that a sport would help me. <mark>At first</mark> I didn't really enjoy it, because I was afraid of making mistakes in front of the others.",
   "The moment I remember best is my first competition. I was really nervous, and I lost my first fight in less than a minute. I was so upset that I wanted to go home immediately. <mark>But then</mark> Luciano sat down next to me and said: “You didn't lose, you learnt something.” <mark>Then</mark> he explained exactly what I had done wrong, calmly, without shouting.",
   "It sounds simple, <mark>but</mark> it changed the way I saw mistakes. <mark>After that</mark>, I started to enjoy training much more, and I became more confident at school too.",
   "<mark>Looking back</mark>, I think he taught me much more than judo. He showed me that a good teacher is patient and believes in you. <mark>What's more</mark>, now that I'm a teacher myself, I often say the same thing to my students when they fail a test. <mark>So, all in all</mark>, he's still an important person for me, even though I haven't seen him for many years."],
  [("Do you think teachers today have the same influence on young people?", "Yes, I think they can, although it's harder, because young people have many other influences, like social media. But a teacher who really listens can still make a big difference."),
   ("Is it better to have a strict teacher or a relaxed one?", "I'd say a teacher should be clear and consistent rather than strict. Students need rules, but they also need to feel they can make mistakes without being judged.")],
  [("He has taught me a lot when I was a child.", "He taught me a lot when I was a child.", "“When I was a child” → past simple.", "tense"),
   ("He was a person very patient.", "He was a very patient person.", "L'aggettivo va prima del nome.", "wo")]),

mono("p4-achievement", "4.3", "Un traguardo di cui vai fiero", "Raccontare un successo e il percorso",
  ["storytelling", "work", "education"], 9,
  "Raccontare un successo mostrando il percorso (difficoltà → sforzo → risultato).",
  "Talk about an achievement you are proud of.",
  ["What did you achieve?", "When was it?", "What difficulties did you have?", "How did you feel?"],
  ["concorso – permanent teacher", "last year – long preparation", "work + study at night", "results online – shouting!", "since then – more confident", "PAST → Since then"],
  ["The achievement I'm most proud of is passing the national teachers' competition, which gave me a permanent position at my school.",
   "<mark>At that time</mark> I was already teaching, but on temporary contracts, so every September I didn't know where I would work. The competition was the only way to get a stable job.",
   "The preparation was really hard. I was working full-time, so I had to study in the evenings and at weekends for several months. <mark>On top of that</mark>, the exam included a written test and a practical lesson in front of a committee, which made me very nervous.",
   "<mark>In the end</mark>, the day the results came out, I was at home and I checked the website about twenty times. When I finally saw my name on the list, I shouted so loudly that my neighbour came to ask if everything was OK!",
   "<mark>Since then</mark>, my life has become much more stable. I can plan my lessons over several years and work on long-term projects with my colleagues. <mark>Looking back</mark>, I think I'm proud not only of the result, but of the fact that I didn't give up when I was tired. <mark>That's why</mark> I'm using the same approach for this English exam."],
  [("Is it important to set goals in life?", "I think so. Goals give you direction and help you stay motivated, but they need to be realistic, otherwise you just get frustrated."),
   ("Do you think people today give up too easily?", "Sometimes, yes. Everything is so fast now that people expect immediate results. But I also see many young people who work really hard for what they want.")],
  [("I'm proud to have passed it.", "I'm proud that I passed it. / I'm proud of passing it.", "Entrambe corrette; scegline una e usala sempre.", ""),
   ("When I have seen my name…", "When I saw my name…", "Momento preciso nel passato.", "tense")]),

mono("p4-difficult", "4.4", "Una situazione difficile", "Un problema e come l'hai risolto",
  ["storytelling", "travel", "strategy"], 9,
  "Raccontare un problema in modo lineare: situazione → problema → soluzione → lezione imparata.",
  "Talk about a difficult situation you had to deal with.",
  ["What was the situation?", "Why was it difficult?", "What did you do?", "What did you learn from it?"],
  ["school trip – Munich", "student lost – station", "phone, police, calm", "found – 40 min", "lesson: plan B, stay calm", "PAST → I learnt"],
  ["I'd like to talk about a difficult situation I had a few years ago, during a school trip to Munich.",
   "I was one of the teachers in charge of a group of about forty students. On the last day we were at the central station, waiting for the train home, <mark>when</mark> we realised that one student was missing.",
   "<mark>At first</mark> I thought he was just in the toilet or buying something, <mark>but</mark> after ten minutes he still wasn't there, and he wasn't answering his phone. The train was leaving in less than an hour, so I was really worried. <mark>Then</mark> I asked my colleague to stay with the group, and I went to the station police.",
   "They were very helpful. They made an announcement in English and German, and about forty minutes later the student appeared. He had got on the wrong underground line and his phone battery was dead. We caught the train with five minutes to spare!",
   "<mark>Looking back</mark>, I learnt two things. <mark>First</mark>, it's essential to stay calm, because the students look at you to understand how serious the situation is. <mark>Second</mark>, you always need a plan B. <mark>Since then</mark>, on every trip, I give all the students a card with my number and a meeting point."],
  [("How do you usually react when something goes wrong?", "I try to stay calm and think about the next step. Getting angry or panicking doesn't solve anything, although of course I don't always manage it!"),
   ("Are school trips worth the effort?", "Definitely. Students learn a lot, not only about the places, but about being independent. And they remember those trips for years.")],
  [("He had took the wrong line.", "He had taken the wrong line.", "Past perfect = had + participio.", "tense"),
   ("I was very worried for him.", "I was very worried about him.", "Worried <strong>about</strong>.", "prep")]),

mono("p4-place", "4.5", "Un luogo speciale", "Descrivere un posto e cosa significa per te",
  ["storytelling", "home", "environment", "sport"], 11,
  "Descrivere un luogo con dettagli sensoriali, senza perdere il filo della storia.",
  "Talk about a place that is special to you.",
  ["Where is it?", "How often do you go there?", "What do you do there?", "Why is it special?"],
  ["river path – Livenza", "5 min from home", "run 2–3 times/week, seasons", "the day I saw a deer / mist", "clears my mind", "PRESENT + one PAST memory"],
  ["The place I'd like to talk about is a path along the Livenza river, just five minutes from my house.",
   "It isn't a famous place at all. It's a simple dirt path between the fields and the water, with trees on both sides. I go there two or three times a week, usually to run, but sometimes just for a walk with my family.",
   "What I love about it is that it changes with the seasons. In autumn the trees turn yellow and red, and in winter, early in the morning, there's often a thick mist over the water, which looks almost magical. I remember one morning last winter, when I was running in the fog, a deer suddenly jumped across the path right in front of me. I stopped, and for a few seconds we just looked at each other.",
   "<mark>Apart from</mark> the beauty, it's special because it's where I think. When I have a problem at work or a difficult decision to make, I go for a run there, and I usually come back with a clearer head.",
   "<mark>So, all in all</mark>, it's a very ordinary place, <mark>but</mark> for me it's the perfect way to switch off. I've lived near it for years and I've never got bored of it."],
  [("Is it important for towns to have green spaces?", "Very. Green spaces are good for people's physical and mental health, and they're free, so everyone can use them."),
   ("Do people spend less time outdoors than in the past?", "I think so, especially children. When I was young we played outside all afternoon, while now many kids spend their free time indoors, in front of a screen.")],
  [("I go there since many years.", "I've been going there for years.", "Da anni → present perfect continuous + for.", "tense"),
   ("It's near to my house.", "It's near my house. / It's close to my house.", "Near senza “to”; close vuole “to”.", "prep")]),

mono("p4-skill", "4.6", "Imparare una nuova abilità", "Un'abilità imparata da adulto",
  ["storytelling", "education", "tech"], 13,
  "Raccontare un processo di apprendimento con connettori di sequenza e il present perfect per i risultati.",
  "Talk about a skill you learnt as an adult.",
  ["What skill was it?", "Why did you decide to learn it?", "How did you learn it?", "How useful has it been?"],
  ["3D printing / design", "school lab – new printer", "online tutorials + trial & error", "first print – disaster", "now: students' projects", "PAST → has been useful"],
  ["I'd like to talk about 3D design and printing, which I learnt a few years ago.",
   "The reason was quite practical. Our school bought a 3D printer for the lab, but nobody really knew how to use it, so it stayed in a corner for months. I thought it was a shame, so I decided to learn.",
   "<mark>At first</mark> I watched lots of online tutorials in the evenings, and <mark>then</mark> I started experimenting. My first print was a complete disaster: the plastic came out like spaghetti and I had to throw everything away! <mark>But</mark> little by little I understood how to set the temperature and the speed, and <mark>eventually</mark> I managed to print a simple box for an electronic circuit.",
   "It has been really useful. Now my students design cases for their own projects, and they're much more motivated when they can take home something they've made. <mark>What's more</mark>, it has helped me understand how they feel when they learn something new and make mistakes.",
   "<mark>So</mark>, the lesson for me is that you're never too old to learn, and that mistakes are part of the process."],
  [("Is it easier to learn new skills today than in the past?", "In a way, yes, because there are so many free resources online. But it's also easy to get distracted, so you need more discipline."),
   ("What skill would you like to learn next?", "I'd like to speak English more fluently, of course! After that, maybe playing the guitar, which I've always wanted to do.")],
  [("I learnt it alone.", "I taught myself. / I learnt it on my own.", "“Da solo” = on my own / by myself.", "calque"),
   ("Eventually I will try.", "I might try at some point.", "“Eventually” = alla fine, non “eventualmente”.", "calque")]),

mono("p4-journey", "4.7", "Un viaggio memorabile", "Raccontare un viaggio, un imprevisto e un ricordo",
  ["storytelling", "travel", "freetime"], 13,
  "Raccontare un viaggio scegliendo UN momento centrale, senza elenchi di luoghi.",
  "Talk about a journey or trip you remember well.",
  ["Where did you go?", "Who did you go with?", "What happened?", "Why do you remember it?"],
  ["Dolomites – hut", "2 friends – summer", "storm – afternoon", "stayed in hut, strangers, cards", "sunrise next morning", "PAST → still talk about it"],
  ["I'd like to talk about a trip to the Dolomites that I did with two friends a few summers ago.",
   "We had planned a two-day hike, and the idea was to sleep in a mountain hut halfway along the route. The first morning was perfect: blue sky, no wind, amazing views.",
   "<mark>However</mark>, in the afternoon the weather changed very quickly. Dark clouds came in and <mark>then</mark> a violent storm started, with thunder and heavy rain. Luckily, we were only about twenty minutes from the hut, so we ran the last part and arrived completely soaked.",
   "The hut was full of other hikers who had had the same problem. There was no signal, so instead of looking at our phones, we spent the evening playing cards and talking with people from Germany and Austria. It was one of the most fun evenings I can remember.",
   "The next morning the sky was clear again, and we watched the sunrise over the mountains. <mark>Looking back</mark>, I remember that trip not for the views, but for the storm and the evening in the hut. We still talk about it every time we meet."],
  [("Do you prefer planned trips or spontaneous ones?", "I like to plan the basics, like transport and where to sleep, but I prefer to leave some free time for surprises. Often the best moments are the ones you didn't plan."),
   ("Is it important to disconnect from technology on holiday?", "I think it is, at least for a few hours a day. That evening in the hut showed me how much better conversations are without phones.")],
  [("We did a trip in the Dolomites.", "We went on a trip to the Dolomites.", "Go on a trip <strong>to</strong>.", "calque"),
   ("We arrived at the hut completely wet like chickens.", "We arrived at the hut completely soaked.", "Niente modi di dire tradotti: “soaked (to the skin)”.", "calque")]),

mono("p4-change", "4.8", "Un cambiamento importante", "Come la tecnologia ha cambiato il tuo lavoro",
  ["storytelling", "tech", "work"], 14,
  "Confrontare passato e presente (used to / now) e dare un'opinione bilanciata.",
  "Talk about how technology has changed your job or daily life.",
  ["What was it like before?", "What has changed?", "Give an example.", "Is the change positive or negative?"],
  ["teaching then vs now", "used to: paper, blackboard", "now: platform, simulators", "example: lockdown lessons", "+ / − balance", "used to → have changed"],
  ["I'd like to talk about how technology has changed my job as a teacher.",
   "When I started teaching, we <mark>used to</mark> do almost everything on paper. We wrote on the blackboard, students copied the circuits into their notebooks, and we recorded marks in a paper register.",
   "Now things are completely different. We have an online register, students receive materials on a digital platform, and in the lab we use simulation software before building a circuit, which saves time and components.",
   "The clearest example was during the lockdown in 2020. From one day to the next, we had to teach online. <mark>At first</mark> it was chaotic, and I spent whole nights learning how to use video-conferencing tools. <mark>But in the end</mark> we managed, and many of those tools are still useful today.",
   "<mark>On the whole</mark>, I think the change has been positive: lessons are more interactive and students can study at their own pace. <mark>On the other hand</mark>, I've noticed that students find it harder to concentrate for a long time, and they sometimes trust the simulator more than their own reasoning. <mark>So</mark>, technology is a great tool, but it doesn't replace a good teacher."],
  [("Will technology replace teachers in the future?", "I don't think so. It can replace some tasks, like correcting simple tests, but students still need someone who motivates them and understands their problems."),
   ("Are older people disadvantaged by technology?", "Sometimes, yes, especially with public services that are only online. I think there should always be an alternative, like a phone number or an office.")],
  [("Before, I was used to write on the blackboard.", "I used to write on the blackboard.", "Abitudine passata = used to + verbo base.", "tense"),
   ("During the lockdown we have taught online.", "During the lockdown we taught online.", "Periodo concluso → past simple.", "tense")]),
]
